namespace FplParser.Tests.UserFriendly
open FParsec
open FplParser
open Microsoft.VisualStudio.TestTools.UnitTesting


[<TestClass>]
type TestUserFriendlyExpressions() =


    [<DataRow("not00", "true")>]
    [<DataRow("not01", "not true")>]
    [<DataRow("not02", "¬true")>]
    [<DataRow("not03", "¬¬true")>]
    [<DataRow("not04", "¬¬¬true")>]
    [<DataRow("not05", "¬ ¬¬true")>]
    [<DataRow("not06", "¬ ¬ ¬true")>]
    [<DataRow("not07", "¬ ¬ ¬ true")>]
    [<DataRow("not02a", "¬(true)")>]
    [<DataRow("not03a", "¬¬(true)")>]
    [<DataRow("not04a", "¬(¬¬(true))")>]
    [<DataRow("not05a", "¬ (¬¬true)")>]
    [<DataRow("not06a", "¬ ¬ ¬(true)")>]
    [<DataRow("not07a", "¬ ¬ ¬ ( true)")>]
    [<TestMethod>]
    member this.TestExprNot(no:string, fplCode) =
        let result = run (predicate .>> eof) fplCode
        let actual = sprintf "%O" result
        printf "%O" actual
        Assert.IsTrue(actual.StartsWith("Success:"))
        
    [<DataRow("is00", ".n is N")>]
    [<DataRow("is01", "¬¬.n is N")>]
    [<DataRow("is02", "..x is N is X")>]
    [<DataRow("is03", "is(n,N)")>]
    [<DataRow("is04", "¬¬is(n, N)")>]
    [<DataRow("is05", "is(is(x , N), X)")>]
    [<DataRow("is06", "is(.x is N, X)")>]
    [<TestMethod>]
    member this.TestIsOperator(no:string, fplCode) =
        let result = run (predicate .>> eof) fplCode
        let actual = sprintf "%O" result
        printf "%O" actual
        Assert.IsTrue(actual.StartsWith("Success:"))

    [<DataRow("and00", ".x ∧ y")>]
    [<DataRow("and01", "¬¬.n ∧ x")>]
    [<DataRow("and02", "..x ∧ y ∧ z")>]
    [<DataRow("and03", "∧(x,y)")>]
    [<DataRow("and04", "¬¬∧(x, y)")>]
    [<DataRow("and05", "∧(∧(x , y), z)")>]
    [<DataRow("and06", "∧(.x ∧ y, z)")>]
    [<TestMethod>]
    member this.TestConjunction(no:string, fplCode) =
        let result = run (predicate .>> eof) fplCode
        let actual = sprintf "%O" result
        printf "%O" actual
        Assert.IsTrue(actual.StartsWith("Success:"))

    [<DataRow("or00", ".x ∨ y")>]
    [<DataRow("or01", "¬¬.n ∨ x")>]
    [<DataRow("or02", "..x ∨ y ∨ z")>]
    [<DataRow("or03", "∨(x,y)")>]
    [<DataRow("or04", "¬¬∨(x, y)")>]
    [<DataRow("or05", "∨(∨(x , y), z)")>]
    [<DataRow("or06", "∨(.x ∨ y, z)")>]
    [<TestMethod>]
    member this.TestDisjunction(no:string, fplCode) =
        let result = run (predicate .>> eof) fplCode
        let actual = sprintf "%O" result
        printf "%O" actual
        Assert.IsTrue(actual.StartsWith("Success:"))

    [<DataRow("all00", "∀ m, n:Nat {((n') = (m'))}")>]
    [<DataRow("all01", "∀ m, n:Nat { true }")>]
    [<DataRow("all02", "∀ m:Nat { true }")>]
    [<DataRow("00", "∀ m, n:Nat {((n') = (m')) ⇒ (n = m)}")>]
    [<DataRow("00", "∀ m, n:Nat {((n') = (m')) ⇒ (n = m)}")>]
    [<DataRow("00", "∀ n:Nat {.true ⇔ false ⩡ (.n is N ⇔ true)}")>]
    [<DataRow("00", "∀ n:Nat {.true ⇔ false ∧ (.n is N ⇔ true)}")>]
    [<DataRow("00", "∀ n:Nat {.true ⇔ false ∨ (.n is N ⇔ true)}")>]
    [<DataRow("00", "∀ n:Nat {.true ⇔ false ⇒ (.n is N ⇔ true)}")>]
    [<DataRow("00", "∀ n:Nat {.true ⇔ false ⇔ (.n is N ⇔ true)}")>]
    [<DataRow("00", "∀ n:Nat {¬(¬.n is N ∧ .true ⩡ false)}")>]
    [<DataRow("00", "∀ x, y:Set {.x is N ⇒ (x = y)}")>]
    [<DataRow("00", "∀ x:obj {¬(.x is N ⇔ false)}")>]
    [<DataRow("00", "∀ x:obj {¬.true ⩡ false ⩡ (.x is N ⇒ false)}")>]
    [<DataRow("00", "∀ x:obj {¬.true ⩡ false ∧ (.x is N ⇒ false)}")>]
    [<DataRow("00", "∀ x:obj {¬.true ⩡ false ∨ (.x is N ⇒ false)}")>]
    [<DataRow("00", "∀ x:obj {¬.true ⩡ false ⇒ (.x is N ⇒ false)}")>]
    [<DataRow("00", "∀ x:obj {¬.true ⩡ false ⇔ (.x is N ⇒ false)}")>]
    [<DataRow("00", "∀ x:obj {.x is N} ⩡ ∃ y:obj {.y is M}")>]
    [<DataRow("00", "∀ x:obj {.x is N} ∧ (¬false ∨ ∃ y:obj {.y is M})")>]
    [<DataRow("00", "∀ x:obj {.x is N} ∧ ∃ y:obj {.y is M}")>]
    [<DataRow("00", "∀ x:obj {.x is N} ∧ ¬∃ y:obj {.y is M}")>]
    [<DataRow("00", "∀ x:obj {.x is N} ∨ (¬false ∧ .true ⩡ false)")>]
    [<DataRow("00", "∀ x:obj {.x is N} ⇒ .true ⩡ false")>]
    [<DataRow("00", "∀ x:obj {.x is N} ⇒ ∃ y:obj {.y is M}")>]
    [<DataRow("00", "∀ x:obj {.x is N} ⇔ ∃ y:obj {.y is M}")>]
    [<DataRow("00", "∀ x:obj {.x is N}")>]
    [<DataRow("00", "∀ y:obj {.y is K} ∧ ∃ n:Nat {.n is M ⩡ true}")>]
    [<DataRow("00", "∀ y:obj {.y is M} ⩡ ∃ n:Nat {.n is K ⩡ true}")>]
    [<DataRow("00", "∀ y:obj {.y is M} ∨ ∃ n:Nat {.n is K ⩡ true}")>]
    [<DataRow("00", "∀ y:obj {.y is M} ⇒ ∀ n:Nat {.n is K ⩡ true}")>]
    [<DataRow("00", "∀ y:obj {.y is M} ⇒ ∃ n:Nat {.n is K ⩡ true}")>]
    [<DataRow("00", "∀ y:obj {.y is M} ⇔ ∀ n:Nat {.n is K ⩡ true}")>]
    [<DataRow("00", "∀ y:obj {.y is M} ⇔ ∃ n:Nat {.n is K ⩡ true}")>]
    [<DataRow("00", "∀ z:obj {∀ y:obj {.y is M} ⩡ (.z is K ⩡ true)}")>]
    [<DataRow("00", "∀ z:obj {∀ y:obj {.y is M} ⇒ (.z is K ⩡ true)}")>]
    [<DataRow("00", "∀ z:obj {∀ y:obj {.y is M} ⇔ (.z is K ⩡ true)}")>]
    [<DataRow("00", "∀ z:obj {∃ y:obj {.y is M} ∧ (.z is K ⩡ true)}")>]
    [<DataRow("00", "∀ z:obj {∃ y:obj {.y is M} ∨ (.z is K ⩡ true)}")>]
    [<TestMethod>]
    member this.TestExprAll(no:string, fplCode) =
        let result = run (predicate .>> eof) fplCode
        let actual = sprintf "%O" result
        printf "%O" actual
        Assert.IsTrue(actual.StartsWith("Success:"))


    [<DataRow("ex01", "∃ x:obj {(x is Nat)}")>] 
    [<DataRow("ex02", "∃ m, n:Nat { true }")>]
    [<DataRow("ex03", "∃ x:obj {.x is N}")>]
    [<DataRow("00", "∃ a:obj {.a is N ⇔ true}")>]
    [<DataRow("00", "∃ n:Nat {.true ⇔ false ⩡ (.n is N ⇔ true)}")>]
    [<DataRow("00", "∃ n:Nat {.true ⇔ false ∧ (.n is N ⇔ true)}")>]
    [<DataRow("00", "∃ n:Nat {.true ⇔ false ∨ (.n is N ⇔ true)}")>]
    [<DataRow("00", "∃ n:Nat {.true ⇔ false ⇒ (.n is N ⇔ true)}")>]
    [<DataRow("00", "∃ n:Nat {.true ⇔ false ⇔ (.n is N ⇔ true)}")>]
    [<DataRow("00", "∃ n:Nat {¬(.n is N ⇒ .true ⩡ false)}")>]
    [<DataRow("00", "∃ n:obj {.n is N}")>]
    [<DataRow("00", "∃ x:obj {¬.true ⩡ false ⩡ (.x is N ⇒ false)}")>]
    [<DataRow("00", "∃ x:obj {¬.true ⩡ false ∧ (.x is N ⇒ false)}")>]
    [<DataRow("00", "∃ x:obj {¬.true ⩡ false ∨ (.x is N ⇒ false)}")>]
    [<DataRow("00", "∃ x:obj {¬.true ⩡ false ⇒ (.x is N ⇒ false)}")>]
    [<DataRow("00", "∃ x:obj {¬.true ⩡ false ⇔ (.x is N ⇒ false)}")>]
    [<DataRow("00", "∃ x:obj {¬.x is N}")>]
    [<DataRow("00", "∃ x:obj {.x is N} ∧ (.true ∨ false ∨ .true ⩡ false)")>]
    [<DataRow("00", "∃ x:obj {x is Nat}")>]
    [<DataRow("00", "∃ x:tpl {.a is M ∧ =(a, $1)}")>]
    [<DataRow("00", "∃ x:tpl {∀ z:obj {.z is K} ⩡ ¬.true ⩡ false}")>]
    [<DataRow("00", "∃ x:tpl {∃ x:obj {.x is M} ∧ .true ⇔ false}")>]
    [<DataRow("00", "∃ x1:obj {¬(x1 is N)}")>]
    [<DataRow("00", "∃ y:obj {∀ z:obj {.z is K} ∧ (.y is M ⩡ true)}")>]
    [<DataRow("00", "∃ y:obj {¬¬.y is M}")>]
    [<DataRow("00", "∃ y:obj {.y is K} ∧ ∀ n:Nat {.n is K ⩡ true}")>]
    [<DataRow("00", "∃ y:obj {.y is M} ∨ ∀ n:Nat {.n is K ⩡ true}")>]
    [<DataRow("00", "∃ y:obj {.y is M} ⇒ ∀ x:obj {.x is N}")>]
    [<DataRow("00", "∃ y:obj {.y is M}")>]
    [<DataRow("00", "∃ z:obj {∀ y:obj {.y is M} ⩡ (.z is K ⩡ true)}")>]
    [<DataRow("00", "∃ z:obj {∀ y:obj {.y is M} ∨ (.z is K ⩡ true)}")>]
    [<DataRow("00", "∃ z:obj {∀ y:obj {.y is M} ⇒ (.z is K ⩡ true)}")>]
    [<DataRow("00", "∃ z:obj {∀ y:obj {.y is M} ⇔ (.z is K ⩡ true)}")>]
    [<TestMethod>]
    member this.TestExprExists(no:string, fplCode) =
        let result = run (predicate .>> eof) fplCode
        let actual = sprintf "%O" result
        printf "%O" actual
        Assert.IsTrue(actual.StartsWith("Success:"))


    [<DataRow("00", "(.A is N ∧ true) ∨ ∃ x:obj {.x is M}")>]
    [<DataRow("00", "(.true ∧ ¬false ∧ .true ⩡ false) ∧ ∀ z:obj {.z is K}")>]
    [<DataRow("00", "((true ⇔ ∃ x:obj {.x is N}) ⩡ .true ⩡ false) ⩡ true")>]
    [<DataRow("00", "((true ⇔ ∃ x:obj {.x is N}) ∧ (true ∧ ¬false)) ∨ ((true ⇔ ∃ x:obj {.x is N}) ∧ (false ⩡ true))")>]
    [<DataRow("00", "(.true ⇔ false ∧ .true ∧ false) ∨ (¬.true ⇔ false ∧ ¬.true ∧ false)")>]
    [<DataRow("00", "(.true ⇔ false ∧ ¬.true ⩡ false) ∨ (¬.true ⇔ false ∧ .true ⩡ false)")>]
    [<DataRow("00", "(.true ⇔ false ∨ (true ∧ ¬false)) ∧ (.true ⇔ false ∨ (false ⩡ true))")>]
    [<DataRow("00", "(∀ x:obj {.x is N} ∧ ∃ y:obj {.y is M}) ∧ .true ⇔ false")>]
    [<DataRow("00", "(∀ x:obj {.x is N} ∧ ∃ y:obj {.y is M}) ∧ true")>]
    [<DataRow("00", "(∀ x:obj {.x is N} ∧ ∃ y:obj {.y is M}) ∨ (∀ x:obj {.x is N} ∧ .true ⇒ false)")>]
    [<DataRow("00", "(∀ x:obj {.x is N} ∧ ∃ y:obj {.y is M}) ∨ (¬∀ x:obj {.x is N} ∧ ¬∃ y:obj {.y is M})")>]
    [<DataRow("00", "(∀ x:obj {.x is N} ∧ ¬∃ y:obj {.y is M}) ∨ (¬∀ x:obj {.x is N} ∧ ∃ y:obj {.y is M})")>]
    [<DataRow("00", "(∀ x:obj {.x is N} ∨ ∃ y:obj {.y is M}) ∧ (∀ x:obj {.x is N} ∨ .true ∨ false)")>]
    [<DataRow("00", "(∃ x:obj {.x is N} ∨ .true ⇔ false) ∨ true")>]
    [<DataRow("00", "(∃ x:obj {.x is N} ⇔ .true ⇔ false) ⇔ ∃ y:obj {.y is M}")>]
    [<DataRow("00", "(¬(∃ x:obj {.x is N} ∧ true) ∨ ¬(true ⇔ false)) ∧ ((∃ x:obj {.x is N} ∧ true) ∨ .true ⇔ false)")>]
    [<DataRow("00", "(¬(true ⩡ false) ∧ .true ⇒ false) ∧ ∃! u:obj {.u is L}")>]
    [<DataRow("00", "(¬(true ⩡ false) ∧ (true ⇔ false)) ∨ (¬.true ⩡ false ∧ (∃! z:obj {.z is N} ∧ true))")>]
    [<DataRow("00", "(¬(true ⩡ false) ∨ (true ⇔ true)) ∧ (¬.true ⩡ false ∨ ∀ z:obj {.z is N})")>]
    [<DataRow("00", "(¬(true ∧ false) ∧ ¬(true ⇒ false)) ∨ (¬¬(true ∧ false) ∧ .true ⇒ false)")>]
    [<DataRow("00", "(¬(true ⇒ false) ∧ (true ⩡ false)) ∨ (¬¬(true ⇒ false) ∧ ¬.true ⩡ false)")>]
    [<DataRow("00", "(¬(true ⇔ false) ∧ (true ⩡ false)) ∨ ((true ⇔ false) ∧ ¬.true ⩡ false)")>]
    [<DataRow("00", "(¬(true ⇔ false) ∧ ¬(true ⩡ false)) ∨ ((true ⇔ false) ∧ .true ⩡ false)")>]
    [<DataRow("00", "(¬(true ⇔ true) ∨ ¬¬(false ⩡ true)) ∧ ((true ⇔ true) ∨ ¬(false ⩡ true))")>]
    [<DataRow("00", "(¬∀ x:obj {.x is N} ∧ ∃ y:obj {.y is M}) ∨ (∀ x:obj {.x is N} ∧ ¬∃ y:obj {.y is M})")>]
    [<DataRow("00", "(¬∀ x:obj {.x is N} ∧ ¬∃ y:obj {.y is M}) ∨ (∀ x:obj {.x is N} ∧ ∃ y:obj {.y is M})")>]
    [<DataRow("00", "(¬∀ x:obj {.x is N} ∨ (true ⩡ false)) ∧ (∀ x:obj {.x is N} ∨ ¬(true ⩡ false))")>]
    [<DataRow("00", "(¬∃ x:obj {.x is N} ∨ (true ⇔ false)) ∧ (∃ x:obj {.x is N} ∨ ¬.true ⇔ false)")>]
    [<DataRow("00", "(¬¬(true ⩡ false) ∧ ¬(true ∧ false)) ∨ (¬(true ⩡ false) ∧ .true ∧ false)")>]
    [<DataRow("00", "(¬¬(true ∧ false) ∨ (true ∨ false)) ∧ (¬(true ∧ false) ∨ ¬.true ∨ false)")>]
    [<DataRow("00", "(¬¬(true ⇔ false) ∧ (true ∧ false)) ∨ (¬(true ⇔ false) ∧ ¬.true ∧ false)")>]
    [<DataRow("00", "(¬¬∀ x:obj {.x is N} ∨ ¬(true ∨ false)) ∧ (¬∀ x:obj {.x is N} ∨ .true ∨ false)")>]
    [<DataRow("00", "(A() -> ind) is A1")>]
    [<DataRow("00", ".true ⩡ false ⩡ true")>]
    [<DataRow("00", ".true ⩡ false ∧ ¬false")>]
    [<DataRow("00", "(true ⩡ false) ∨ (∀ x:obj {.x is N} ⇔ false)")>]
    [<DataRow("00", ".true ⩡ false ⇒ .true ⇒ false")>]
    [<DataRow("00", ".true ⩡ false ⇒ .true ⇔ false")>]
    [<DataRow("00", ".true ⩡ false ⇔ (true ⇔ ∃ x:obj {.x is N})")>]
    [<DataRow("00", ".true ∧ false ∧ .true ⇒ false")>]
    [<DataRow("00", ".true ∧ false ∧ .true ⇔ false")>]
    [<DataRow("00", ".true ∧ false ∧ ¬¬∃ x:obj {.x is N}")>]
    [<DataRow("00", ".true ∧ false ∧ true")>]
    [<DataRow("00", "(true ∧ true) ∧ false")>]
    [<DataRow("00", ".true ∨ false ∨ true")>]
    [<DataRow("00", ".true ∨ false ⇔ ¬false")>]
    [<DataRow("00", ".true ⇒ false ⩡ (∃ x:obj {.x is N} ∧ true)")>]
    [<DataRow("00", ".true ⇒ false ⩡ .true ∧ false")>]
    [<DataRow("00", ".true ⇒ false ∧ .true ∧ false")>]
    [<DataRow("00", ".true ⇒ false ⇔ .true ∧ false")>]
    [<DataRow("00", ".true ⇔ false ⩡ .true ⩡ false")>]
    [<DataRow("00", ".true ⇔ false ⩡ ∃ x:obj {.x is N ⇔ true}")>]
    [<DataRow("00", "(true ⇔ false) ∧ ((true ∧ ¬false) ∨ .true ⇒ false)")>]
    [<DataRow("00", ".true ⇔ false ∧ .true ⩡ false")>]
    [<DataRow("00", ".true ⇔ false ∧ ∀ x:obj {.x is N ⇔ true}")>]
    [<DataRow("00", ".true ⇔ false ∧ ∃ x:obj {.x is N ⇔ true}")>]
    [<DataRow("00", ".true ⇔ false ∧ ¬.true ⩡ false")>]
    [<DataRow("00", ".true ⇔ false ∨ (.true ⩡ false ∧ (∃ n:obj {.n is N} ∧ true))")>]
    [<DataRow("00", ".true ⇔ false ∨ (∃ y:obj {.y is M} ∨ true)")>]
    [<DataRow("00", ".true ⇔ false ∨ ∀ x:obj {.x is N ⇔ true}")>]
    [<DataRow("00", ".true ⇔ false ∨ ∃ x:obj {.x is N ⇔ true}")>]
    [<DataRow("00", ".true ⇔ false ∨ ∃ x:obj {.x is N}")>]
    [<DataRow("00xx", ".true ⇔ false ⇒ (..A is N ∧ true)")>]
    [<DataRow("00", ".true ⇔ false ⇒ .true ∧ false")>]
    [<DataRow("00", ".true ⇔ false ⇒ .true ⇔ false")>]
    [<DataRow("00", ".true ⇔ false ⇒ ∀ u:obj {.u is K}")>]
    [<DataRow("00", ".true ⇔ false ⇒ ∀ x:obj {.x is N ⇔ true}")>]
    [<DataRow("00", ".true ⇔ false ⇒ ∃ x:obj {.x is N ⇔ true}")>]
    [<DataRow("00", "(true ⇔ false) ⇔ .true ⩡ false")>]
    [<DataRow("00", ".true ⇔ false ⇔ ∀ x:obj {.x is N ⇔ true}")>]
    [<DataRow("00", ".true ⇔ false ⇔ ∃ x:obj {.x is N ⇔ true}")>]
    [<DataRow("00", ".true ⇔ false ⇔ true")>]

    [<DataRow("00", "¬(.A is N ⇔ true) ⇒ ∃ x:obj {.x is M}")>]
    [<DataRow("00", "¬((true ⩡ false) ∧ .true ⇒ false)")>]
    [<DataRow("00", "¬(.true ∧ false ∧ ∃ x:obj {.x is N})")>]
    [<DataRow("00", "¬((true ⇒ false) ⩡ .true ∧ false)")>]
    [<DataRow("00", "¬((true ⇒ false) ∨ .true ∧ false)")>]
    [<DataRow("00", "¬(.true ⇒ false ⇔ ∀ z:obj {.z is K})")>]
    [<DataRow("00", "¬((true ⇔ false) ⩡ .true ⩡ false)")>]
    [<DataRow("00", "¬(.true ⇔ false ∧ ∀ x:obj {.x is N})")>]
    [<DataRow("00", "¬(.true ⇔ false ∨ ∃ x:obj {.x is N})")>]
    [<DataRow("00", "¬((true ⇔ false) ⇒ .true ⩡ false)")>]
    [<DataRow("00", "¬((true ⇔ false) ⇔ .true ⩡ false)")>]
    [<DataRow("00", "¬(∀ x:obj {.x is N} ⩡ ∃ y:obj {.y is M})")>]
    [<DataRow("00", "¬(∀ x:obj {.x is N} ∨ .true ⩡ false)")>]
    [<DataRow("00", "¬(∀ x:obj {.x is N} ⇒ ∃ y:obj {.y is M})")>]
    [<DataRow("00", "¬(∀ x:obj {.x is N} ⇒ ¬.true ⇔ false)")>]
    [<DataRow("00", "¬(∀ x:obj {.x is N} ⇔ ∃ y:obj {.y is M})")>]
    [<DataRow("00", "¬(∃ x:obj {.x is M} ⇒ ¬¬.true ⩡ false)")>]
    [<DataRow("00", "¬(¬.true ⇒ false ⇒ ∀ z:obj {.z is K})")>]
    [<DataRow("00", "¬(¬.true ⇒ false ⇒ ¬∀ z:obj {.z is K})")>]
    [<DataRow("00", "¬(¬(true ⇔ false) ∨ ¬.true ⩡ false)")>]
    [<DataRow("00", "¬(¬∀ x:obj {.x is N} ∨ ¬∃ y:obj {.y is M})")>]
    [<DataRow("00", "¬(¬¬∃ x:obj {.x is N} ∨ ¬.true ⇒ false)")>]
    [<DataRow("00", "¬.true ⩡ false ⩡ ∃ z:obj {.z is N ⇒ false}")>]
    [<DataRow("00", "¬.true ⩡ false ∧ ∀ z:obj {.z is N ⇒ false}")>]
    [<DataRow("00", "¬.true ⩡ false ∧ ∃ z:obj {.z is N ⇒ false}")>]
    [<DataRow("00", "¬.true ⩡ false ∨ ∀ z:obj {.z is N ⇒ false}")>]
    [<DataRow("00", "¬.true ⩡ false ∨ ∃ z:obj {.z is N ⇒ false}")>]
    [<DataRow("00", "¬(true ⩡ false) ⇒ (∀ z:obj {.z is N} ⇒ false)")>]
    [<DataRow("00", "¬.true ⩡ false ⇒ ∀ z:obj {.z is N ⇒ false}")>]
    [<DataRow("00", "¬.true ⩡ false ⇒ ∃ z:obj {.z is N ⇒ false}")>]
    [<DataRow("00", "¬.true ⩡ false ⇔ ∀ z:obj {.z is N ⇒ false}")>]
    [<DataRow("00", "¬.true ⩡ false ⇔ ∃ z:obj {.z is N ⇒ false}")>]
    [<DataRow("00", "¬.true ⩡ false")>]
    [<DataRow("00", "¬(true ∧ ¬false) ∨ (∃ x:obj {.x is N} ∨ true)")>]
    [<DataRow("00", "¬.true ∧ false")>]
    [<DataRow("00", "¬(true ⇒ false) ∧ ¬.true ∧ false")>]
    [<DataRow("00", "¬.true ⇔ false ∧ ¬∃ x:obj {.x is N}")>]
    [<DataRow("00", "¬(true ⇔ false) ∨ ¬.true ⇒ false")>]
    [<DataRow("00", "¬.true ⇔ false")>]
    [<DataRow("00", "¬∀ n:Nat {.n is N ∧ .true ⩡ false}")>]
    [<DataRow("00", "¬∀ x:obj {.x is N ⇔ true}")>]
    [<DataRow("00", "¬∀ x:obj {.x is N} ∧ ∀ x:obj {.x is N}")>]
    [<DataRow("00", "¬∀ x:obj {.x is N} ∧ ¬.true ⩡ false")>]
    [<DataRow("00", "¬∀ x:obj {.x is N} ∨ ∃ y:obj {.y is M}")>]
    [<DataRow("00", "¬∀ x:obj {.x is N} ∨ ¬∃ y:obj {¬.y is M}")>]
    [<DataRow("00", "¬∀ x:obj {.x is N} ⇒ (true ∧ ¬false)")>]
    [<DataRow("00", "¬∀ x:obj {.x is N}")>]
    [<DataRow("00", "¬∃ n:Nat {.n is N ∧ .true ⩡ false}")>]
    [<DataRow("00", "¬∃ x:obj {.x is N ⇔ true}")>]
    [<DataRow("00", "¬¬(true ⩡ false) ∨ .true ⇔ false")>]
    [<DataRow("00", "¬¬true ∨ ¬.true ⩡ false")>]
    [<DataRow("00", "¬true ∨ (.true ⇒ false ∧ ∃ y:obj {.y is N})")>]
    [<DataRow("00", "A is A1")>]
    [<DataRow("00", "A() is A1")>]
    [<DataRow("00", "false ⩡ true")>]
    [<DataRow("00", "false ∧ true")>]
    [<DataRow("00", "false ∨ true")>]
    [<DataRow("00", "false ⇔ true")>]
    [<DataRow("00", "false")>]
    [<DataRow("00", "q ⇒ (¬(true ⩡ false) ∧ .true ⇔ false)")>]
    [<DataRow("00", "q ⇒ ∀ x:obj {.x is N}")>]
    [<DataRow("00", "true ⩡ false")>]
    [<DataRow("00", "true ∧ (false ⩡ true)")>]
    [<DataRow("00", "true ∧ ¬false")>]
    [<DataRow("00", "true ∧ false")>]
    [<DataRow("00", "true ∨ false")>]
    [<DataRow("00", "true ⇒ false")>]
    [<DataRow("00", "true ⇔ .false ⩡ true")>]
    [<DataRow("00", "true ⇔ ∃ y:obj {.y is M}")>]
    [<DataRow("00", "true ⇔ ¬false")>]
    [<DataRow("00", "true ⇔ false")>]
    [<DataRow("00", "true")>]
    [<DataRow("00", "undet")>]
    [<TestMethod>]
    member this.TestExprMixed(no:string, fplCode) =
        let result = run (predicate .>> eof) fplCode
        let actual = sprintf "%O" result
        printf "%O" actual
        Assert.IsTrue(actual.StartsWith("Success:"))



