namespace Diagnostics.ProofRelated

open Microsoft.VisualStudio.TestTools.UnitTesting
open Fpl.Errors.Diagnostics
open Fpl.Interpreter.Helpers.Debug
open TestFplInterpreter.Helpers.Common

(* PR001
   Purpose: Report that a justification item of an expected kind was not found at the referenced location.
   What it indicates: A justification referenced a block but the actual block present is of a different, incompatible type.
   Use: Helps locate incorrect justification targets so the author can reference the correct block kind or adjust the justification form.
   Action / Treat: Fix the justification to point to the appropriate block type or change the target block to the expected kind. PR001 is an error that must be resolved for correct justification processing. *)

[<TestClass>]
type TestPR001() =

    [<DataRow("00", "def cl A {intr} thm T {true} proof T$1 {1. bydef A |- trivial }", 0)>]
    [<DataRow("00a", "def cl A {intr} thm T {true} proof T$1 {1. A |- trivial }", 1)>]
    [<DataRow("00b", "def cl A {intr} thm T {true} proof T$1 {1. byax A |- trivial }", 1)>]
    [<DataRow("00c", "def cl A {intr} thm T {true} proof T$1 {1. byconj A |- trivial }", 1)>]
    [<DataRow("00d", "def cl A {intr} thm T {true} proof T$1 {1. byinf A |- trivial }", 1)>]
    [<DataRow("00e", "thm A {true} thm T {true} proof T$1 {1. bydef A |- trivial }", 1)>]
    [<DataRow("00f", "prop A {true} thm T {true} proof T$1 {1. bydef A |- trivial }", 1)>]
    [<DataRow("00g", "lem A {true} thm T {true} proof T$1 {1. bydef A |- trivial }", 1)>]
    [<DataRow("00h", "cor A$1 {true} thm T {true} proof T$1 {1. bydef A |- trivial }", 1)>]
    [<DataRow("00i", "proof A$1 {1: trivial}thm T {true} proof T$1 {1. bydef A |- trivial }", 1)>]
    [<DataRow("00j", "ax A {true} thm T {true} proof T$1 {1. bydef A |- trivial }", 1)>]
    [<DataRow("00k", "inf A {pre:true con:true} thm T {true} proof T$1 {1. bydef A |- trivial }", 1)>]
    [<DataRow("00l", """loc A := !tex: ""; thm T {true} proof T$1 {1. bydef A |- trivial }""", 1)>]
    [<DataRow("00m", "ext A x@/\d+/ -> obj {ret x} thm T {true} proof T$1 {1. bydef A |- trivial }", 1)>]
    [<DataRow("00n", "cor A$1 {true} thm T {true} proof T$1 {1. bydef A |- trivial }", 1)>]
    [<DataRow("00o", "proof A$1 {1: trivial}thm T {true} proof T$1 {1. bydef A |- trivial }", 1)>]
    [<DataRow("01", "def pred A() {intr} thm T {true} proof T$1 {1. bydef A |- trivial }", 0)>]
    [<DataRow("01a", "def pred A() {intr} thm T {true} proof T$1 {1. A |- trivial }", 1)>]
    [<DataRow("01b", "def pred A() {intr} thm T {true} proof T$1 {1. byax A |- trivial }", 1)>]
    [<DataRow("01c", "def pred A() {intr} thm T {true} proof T$1 {1. byconj A |- trivial }", 1)>]
    [<DataRow("01d", "def pred A() {intr} thm T {true} proof T$1 {1. byinf A |- trivial }", 1)>]
    [<DataRow("02", "def func A()->obj {intr} thm T {true} proof T$1 {1. bydef A |- trivial }", 0)>]
    [<DataRow("02a", "def func A()->obj {intr} thm T {true} proof T$1 {1. A |- trivial }", 1)>]
    [<DataRow("02b", "def func A()->obj {intr} thm T {true} proof T$1 {1. byax A |- trivial }", 1)>]
    [<DataRow("02c", "def func A()->obj {intr} thm T {true} proof T$1 {1. byconj A |- trivial }", 1)>]
    [<DataRow("02d", "def func A()->obj {intr} thm T {true} proof T$1 {1. byinf A |- trivial }", 1)>]
    [<DataRow("03", "ax A {true} thm T {true} proof T$1 {1. byax A |- trivial }", 0)>]
    [<DataRow("03a", "ax A {true} thm T {true} proof T$1 {1. A |- trivial }", 1)>]
    [<DataRow("03b", "ax A {true} thm T {true} proof T$1 {1. byconj A |- trivial }", 1)>]
    [<DataRow("03c", "ax A {true} thm T {true} proof T$1 {1. byinf A |- trivial }", 1)>]
    [<DataRow("03d", "ax A {true} thm T {true} proof T$1 {1. bydef A |- trivial }", 1)>]
    [<DataRow("03e", "thm A {true} thm T {true} proof T$1 {1. byax A |- trivial }", 1)>]
    [<DataRow("03f", "prop A {true} thm T {true} proof T$1 {1. byax A |- trivial }", 1)>]
    [<DataRow("03g", "lem A {true} thm T {true} proof T$1 {1. byax A |- trivial }", 1)>]
    [<DataRow("03h", "cor A$1 {true} thm T {true} proof T$1 {1. byax A |- trivial }", 1)>]
    [<DataRow("03i", "proof A$1 {1: trivial}thm T {true} proof T$1 {1. byax A |- trivial }", 1)>]
    [<DataRow("03j", "def pred A() {true} thm T {true} proof T$1 {1. byax A |- trivial }", 1)>]
    [<DataRow("03k", "def func A()->obj {intr} thm T {true} proof T$1 {1. byax A |- trivial }", 1)>]
    [<DataRow("03l", "def cl A {intr} thm T {true} proof T$1 {1. byax A |- trivial }", 1)>]
    [<DataRow("03m", "conj A {true} thm T {true} proof T$1 {1. byax A |- trivial }", 1)>]
    [<DataRow("03n", "inf A {pre:true con:true} thm T {true} proof T$1 {1. byax A |- trivial }", 1)>]
    [<DataRow("03o", """loc A := !tex: ""; thm T {true} proof T$1 {1. byax A |- trivial }""", 1)>]
    [<DataRow("03p", "ext A x@/\d+/ -> obj {ret x} thm T {true} proof T$1 {1. byax A |- trivial }", 1)>]
    [<DataRow("04", "conj A {true} thm T {true} proof T$1 {1. byconj A |- trivial }", 0)>]
    [<DataRow("04a", "conj A {true} thm T {true} proof T$1 {1. A |- trivial }", 1)>]
    [<DataRow("04b", "conj A {true} thm T {true} proof T$1 {1. byax A |- trivial }", 1)>]
    [<DataRow("04c", "conj A {true} thm T {true} proof T$1 {1. byinf A |- trivial }", 1)>]
    [<DataRow("04d", "conj A {true} thm T {true} proof T$1 {1. bydef A |- trivial }", 1)>]
    [<DataRow("04e", "thm A {true} thm T {true} proof T$1 {1. byconj A |- trivial }", 1)>]
    [<DataRow("04f", "prop A {true} thm T {true} proof T$1 {1. byconj A |- trivial }", 1)>]
    [<DataRow("04g", "lem A {true} thm T {true} proof T$1 {1. byconj A |- trivial }", 1)>]
    [<DataRow("04h", "cor A$1 {true} thm T {true} proof T$1 {1. byconj A |- trivial }", 1)>]
    [<DataRow("04i", "proof A$1 {1: trivial}thm T {true} proof T$1 {1. byconj A |- trivial }", 1)>]
    [<DataRow("04j", "def pred A() {true} thm T {true} proof T$1 {1. byconj A |- trivial }", 1)>]
    [<DataRow("04k", "def func A()->obj {intr} thm T {true} proof T$1 {1. byconj A |- trivial }", 1)>]
    [<DataRow("04l", "def cl A {intr} thm T {true} proof T$1 {1. byconj A |- trivial }", 1)>]
    [<DataRow("04m", "ax A {true} thm T {true} proof T$1 {1. byconj A |- trivial }", 1)>]
    [<DataRow("04n", "inf A {pre:true con:true} thm T {true} proof T$1 {1. byconj A |- trivial }", 1)>]
    [<DataRow("04o", """loc A := !tex: ""; thm T {true} proof T$1 {1. byconj A |- trivial }""", 1)>]
    [<DataRow("04p", "ext A x@/\d+/ -> obj {ret x} thm T {true} proof T$1 {1. byconj A |- trivial }", 1)>]
    [<DataRow("05", "thm A {true} thm T {true} proof T$1 {1. A |- trivial }", 0)>]
    [<DataRow("05a", "thm A {true} thm T {true} proof T$1 {1. A |- trivial }", 0)>]
    [<DataRow("05b", "thm A {true} thm T {true} proof T$1 {1. bydef A |- trivial }", 1)>]
    [<DataRow("05c", "thm A {true} thm T {true} proof T$1 {1. byinf A |- trivial }", 1)>]
    [<DataRow("05d", "thm A {true} thm T {true} proof T$1 {1. byconj A |- trivial }", 1)>]
    [<DataRow("05e", "cor A$1 {true} thm T {true} proof T$1 {1. A |- trivial }", 1)>]
    [<DataRow("05f", "proof A$1 {1: trivial}thm T {true} proof T$1 {1. A |- trivial }", 1)>]
    [<DataRow("05g", "def pred A() {true} thm T {true} proof T$1 {1. A |- trivial }", 1)>]
    [<DataRow("05e", "def func A()->obj {intr} thm T {true} proof T$1 {1. A |- trivial }", 1)>]
    [<DataRow("05f", "def cl A {intr} thm T {true} proof T$1 {1. A |- trivial }", 1)>]
    [<DataRow("05g", "conj A {true} thm T {true} proof T$1 {1. A |- trivial }", 1)>]
    [<DataRow("05h", "inf A {pre:true con:true} thm T {true} proof T$1 {1. A |- trivial }", 1)>]
    [<DataRow("05i", """loc A := !tex: ""; thm T {true} proof T$1 {1. A |- trivial }""", 1)>]
    [<DataRow("05j", "ext A x@/\d+/ -> obj {ret x} thm T {true} proof T$1 {1. A |- trivial }", 1)>]
    [<DataRow("06", "lem A {true} thm T {true} proof T$1 {1. A |- trivial }", 0)>]
    [<DataRow("06a", "lem A {true} thm T {true} proof T$1 {1. A |- trivial }", 0)>]
    [<DataRow("06b", "lem A {true} thm T {true} proof T$1 {1. bydef A |- trivial }", 1)>]
    [<DataRow("06c", "lem A {true} thm T {true} proof T$1 {1. byinf A |- trivial }", 1)>]
    [<DataRow("06d", "lem A {true} thm T {true} proof T$1 {1. byconj A |- trivial }", 1)>]
    [<DataRow("07", "prop A {true} thm T {true} proof T$1 {1. A |- trivial }", 0)>]
    [<DataRow("07a", "prop A {true} thm T {true} proof T$1 {1. bydef A |- trivial }", 1)>]
    [<DataRow("07b", "prop A {true} thm T {true} proof T$1 {1. byinf A |- trivial }", 1)>]
    [<DataRow("07c", "prop A {true} thm T {true} proof T$1 {1. byconj A |- trivial }", 1)>]
    [<DataRow("08", "inf A {pre: true con: true} thm T {true} proof T$1 {1. byinf A |- trivial }", 0)>]
    [<DataRow("08a", "inf A {pre: true con: true} thm T {true} proof T$1 {1. A |- trivial }", 1)>]
    [<DataRow("08b", "inf A {pre: true con: true} thm T {true} proof T$1 {1. byax A |- trivial }", 1)>]
    [<DataRow("08c", "inf A {pre: true con: true} thm T {true} proof T$1 {1. bydef A |- trivial }", 1)>]
    [<DataRow("08d", "thm A {true} thm T {true} proof T$1 {1. byinf A |- trivial }", 1)>]
    [<DataRow("08e", "prop A {true} thm T {true} proof T$1 {1. byinf A |- trivial }", 1)>]
    [<DataRow("08f", "lem A {true} thm T {true} proof T$1 {1. byinf A |- trivial }", 1)>]
    [<DataRow("08g", "cor A$1 {true} thm T {true} proof T$1 {1. byinf A |- trivial }", 1)>]
    [<DataRow("08h", "proof A$1 {1: trivial}thm T {true} proof T$1 {1. byinf A |- trivial }", 1)>]
    [<DataRow("08i", "def pred A() {true} thm T {true} proof T$1 {1. byinf A |- trivial }", 1)>]
    [<DataRow("08j", "def func A()->obj {intr} thm T {true} proof T$1 {1. byinf A |- trivial }", 1)>]
    [<DataRow("08k", "def cl A {intr} thm T {true} proof T$1 {1. byinf A |- trivial }", 1)>]
    [<DataRow("08l", "ax A {true} thm T {true} proof T$1 {1. byinf A |- trivial }", 1)>]
    [<DataRow("08m", """loc A := !tex: ""; thm T {true} proof T$1 {1. byinf A |- trivial }""", 1)>]
    [<DataRow("08n", "ext A x@/\d+/ -> obj {ret x} thm T {true} proof T$1 {1. byinf A |- trivial }", 1)>]
    [<DataRow("09", "proof A$1 {1: trivial } thm T {true} proof T$1 {1. A$1:1 |- trivial }", 0)>]
    [<DataRow("09a", "cor A$1 {true} thm T {true} proof T$1 {1. A$1:1 |- trivial }", 1)>]
    [<DataRow("09b", "thm A {true} thm T {true} proof T$1 {1. A$1:1 |- trivial }", 1)>]
    [<DataRow("09c", "thm A {true} proof A$1 {1: trivial}thm T {true} proof T$1 {1. A$1:1 |- trivial }", 0)>]
    [<DataRow("09d", "inf A {pre: true con: true} thm T {true} proof T$1 {1. A$1:1 |- trivial }", 1)>]
    [<DataRow("09e", "prop A {true} thm T {true} proof T$1 {1. A$1:1 |- trivial }", 1)>]
    [<DataRow("09f", "lem A {true} thm T {true} proof T$1 {1. A$1:1 |- trivial }", 1)>]
    [<DataRow("09g", "cor A$1 {true} thm T {true} proof T$1 {1. A$1:1 |- trivial }", 1)>]
    [<DataRow("09h", "def pred A() {true} thm T {true} proof T$1 {1. A$1:1 |- trivial }", 1)>]
    [<DataRow("09i", "def func A()->obj {intr} thm T {true} proof T$1 {1. A$1:1 |- trivial }", 1)>]
    [<DataRow("09j", "def cl A {intr} thm T {true} proof T$1 {1. A$1:1 |- trivial }", 1)>]
    [<DataRow("09k", "ax A {true} thm T {true} proof T$1 {1. A$1:1 |- trivial }", 1)>]
    [<DataRow("09l", """loc A := !tex: ""; thm T {true} proof T$1 {1. A$1:1 |- trivial }""", 1)>]
    [<DataRow("09m", "ext A x@/\d+/ -> obj {ret x} thm T {true} proof T$1 {1. A$1:1 |- trivial }", 1)>]
    [<DataRow("10", "cor A$1 {true} thm T {true} proof T$1 {1. bycor A$1 |- trivial }", 0)>]
    [<DataRow("10a", "proof A$1 {1: trivial}thm T {true} proof T$1 {1. bycor A$1 |- trivial }", 1)>]
    [<DataRow("10b", "thm A {true} thm T {true} proof T$1 {1. bycor A$1 |- trivial }", 1)>]
    [<DataRow("10c", "thm A {true} proof A$1 {1: trivial}thm T {true} proof T$1 {1. bycor A$1 |- trivial }", 1)>]
    [<DataRow("10c_", "thm A {true} cor A$1 {true} thm T {true} proof T$1 {1. bycor A$1 |- trivial }", 0)>]
    [<DataRow("10d", "inf A {pre: true con: true} thm T {true} proof T$1 {1. bycor A$1 |- trivial }", 1)>]
    [<DataRow("10e", "prop A {true} thm T {true} proof T$1 {1. bycor A$1 |- trivial }", 1)>]
    [<DataRow("10f", "lem A {true} thm T {true} proof T$1 {1. bycor A$1 |- trivial }", 1)>]
    [<DataRow("10g", "proof A$1 {1: trivial}thm T {true} proof T$1 {1. bycor A$1 |- trivial }", 1)>]
    [<DataRow("10h", "def pred A() {true} thm T {true} proof T$1 {1. bycor A$1 |- trivial }", 1)>]
    [<DataRow("10i", "def func A()->obj {intr} thm T {true} proof T$1 {1. bycor A$1 |- trivial }", 1)>]
    [<DataRow("10j", "def cl A {intr} thm T {true} proof T$1 {1. bycor A$1 |- trivial }", 1)>]
    [<DataRow("10k", "ax A {true} thm T {true} proof T$1 {1. bycor A$1 |- trivial }", 1)>]
    [<DataRow("10l", """loc A := !tex: ""; thm T {true} proof T$1 {1. bycor A$1 |- trivial }""", 1)>]
    [<DataRow("10m", "ext A x@/\d+/ -> obj {ret x} thm T {true} proof T$1 {1. bycor A$1 |- trivial }", 1)>]
    
    [<DataRow("1a", "ax A {true} thm T {true} proof T$1 {1. bydef A |- trivial }", 1)>]
    [<DataRow("1b", "conj A {true} thm T {true} proof T$1 {1. bydef A |- trivial }", 1)>]
    [<DataRow("1c", "thm A {true} thm T {true} proof T$1 {1. bydef A |- trivial }", 1)>]
    [<DataRow("1d", "lem A {true} thm T {true} proof T$1 {1. bydef A |- trivial }", 1)>]
    [<DataRow("1e", "prop A {true} thm T {true} proof T$1 {1. bydef A |- trivial }", 1)>]
        
    [<DataRow("1j", "inf A {pre: true con: true} thm T {true} proof T$1 {1. bydef A |- trivial }", 1)>]
    [<DataRow("0a", "def cl A {intr} thm T {true} proof T$1 {1. A$1:1 |- trivial }", 1)>]
    [<DataRow("0b", "def pred A() {intr} thm T {true} proof T$1 {1. A$1:1 |- trivial }", 1)>]
    [<DataRow("0c", "def func A()->obj {intr} thm T {true} proof T$1 {1. A$1:1 |- trivial }", 1)>]
    [<DataRow("1a", "ax A {true} thm T {true} proof T$1 {1. A$1:1 |- trivial }", 1)>]
    [<DataRow("1b", "conj A {true} thm T {true} proof T$1 {1. A$1:1 |- trivial }", 1)>]
    [<DataRow("1c", "thm A {true} thm T {true} proof T$1 {1. A$1:1 |- trivial }", 1)>]
    [<DataRow("1d", "lem A {true} thm T {true} proof T$1 {1. A$1:1 |- trivial }", 1)>]
    [<DataRow("1e", "prop A {true} thm T {true} proof T$1 {1. A$1:1 |- trivial }", 1)>]
    [<DataRow("1f", "cor A$1 {true} thm T {true} proof T$1 {1. A$1:1 |- trivial }", 1)>]
    [<DataRow("1f_", "thm A {true} cor A$1 {true} thm T {true} proof T$1 {1. A$1:1 |- trivial }", 1)>]
    [<DataRow("1j", "inf A {pre: true con: true} thm T {true} proof T$1 {1. A$1:1 |- trivial }", 1)>]
    [<DataRow("2j", "cor A$1 {true} thm T {true} proof T$1 {1. A |- trivial }", 1)>]
    [<DataRow("3k", "proof A$1 {1: trivial}thm T {true} proof T$1 {1. A$1 |- trivial }", 1)>]
    [<DataRow("2k", "proof A$1 {1: trivial}thm T {true} proof T$1 {1. A |- trivial }", 1)>]
    [<DataRow("3a", "def cl A {intr} thm T {true} proof T$1 {1. A$1 |- trivial }", 1)>]
    [<DataRow("3b", "def pred A() {intr} thm T {true} proof T$1 {1. A$1 |- trivial }", 1)>]
    [<DataRow("3c", "def func A()->obj {intr} thm T {true} proof T$1 {1. A$1 |- trivial }", 1)>]
    [<DataRow("3d", "ax A {true} thm T {true} proof T$1 {1. A$1 |- trivial }", 1)>]
    [<DataRow("3e", "conj A {true} thm T {true} proof T$1 {1. A$1 |- trivial }", 1)>]
    [<DataRow("3f", "thm A {true} thm T {true} proof T$1 {1. A$1 |- trivial }", 1)>]
    [<DataRow("3g", "lem A {true} thm T {true} proof T$1 {1. A$1 |- trivial }", 1)>]
    [<DataRow("3h", "prop A {true} thm T {true} proof T$1 {1. A$1 |- trivial }", 1)>]
    [<DataRow("3i", "inf A {pre: true con: true} thm T {true} proof T$1 {1. A$1 |- trivial }", 1)>]
  
    [<DataRow("z2k_", "thm A {true} proof A$1 {1: trivial}thm T {true} proof T$1 {1. A |- trivial }", 0)>]
    [<DataRow("z3j", "cor A$1 {true} thm T {true} proof T$1 {1. A$1 |- trivial }", 0)>]
    [<DataRow("z0a", "def cl A {intr} thm T {true} proof T$1 {1. bydef A |- trivial }", 0)>]
    [<DataRow("z0b", "def pred A() {intr} thm T {true} proof T$1 {1. bydef A |- trivial }", 0)>]
    [<DataRow("z0c", "def func A()->obj {intr} thm T {true} proof T$1 {1. bydef A |- trivial }", 0)>]

    [<DataRow("z1g_", "thm A {true} proof A$1 {1: trivial } thm T {true} proof T$1 {1. A$1:1 |- trivial }", 0)>]
    [<DataRow("z1h_", "thm A {true} proof A$1 {1: trivial } thm T {true} proof T$1 {1. A$1:2 |- trivial }", 0)>]
    [<DataRow("z2j_", "thm A {true} cor A$1 {true} thm T {true} proof T$1 {1. A |- trivial }", 0)>]
    [<DataRow("z3j_", "thm A {true} cor A$1 {true} thm T {true} proof T$1 {1. A$1 |- trivial }", 0)>]
    [<DataRow("99", "uses Fpl.Commons.Structures ", 0)>]
    [<TestMethod>]
    member this.TestPR001(no:string, fplCode:string, expected) =
        if offlineWatcher.OfflineMode && fplCode.StartsWith("uses Fpl.") then 
            ()
        else
            let code = PR001 ("", "")
            runTestHelper "TestPR001.fpl" fplCode code expected
    

