<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <GenerateProgramFile>false</GenerateProgramFile>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <SatelliteResourceLanguages>en</SatelliteResourceLanguages>

        <RepositoryUrl>https://github.com/bookofproofs/fpl.net</RepositoryUrl>
        <FsDocsLicenseLink>https://github.com/bookofproofs/fpl.net/LICENSE.md</FsDocsLicenseLink>
        <PackageProjectUrl>https://github.com/bookofproofs/fpl.net/Fpl</PackageProjectUrl>


    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FParsec" Version="1.1.1" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Fpl0Base\Fpl0Base.fsproj" />
        <ProjectReference Include="..\Fpl1Parser\Fpl1Parser.fsproj" />
        <ProjectReference Include="..\TestSharedConfig\TestSharedConfig.fsproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Update="FSharp.Core" Version="10.1.301" />
    </ItemGroup>

</Project>
