namespace Diagnostics.VariableRelated

open System.IO
open Microsoft.VisualStudio.TestTools.UnitTesting
open Fpl.Errors.Diagnostics
open Fpl.Interpreter.Helpers.Debug
open FplInterpreter.Main
open TestFplInterpreter.Helpers.Common
open TestSharedConfig


[<TestClass>]
type TestVAR04() =

    [<DataRow("01", "def pred T(x:obj) {true}", 1)>]
    [<DataRow("01a", "def pred T(x:obj) {intr}", 0)>]
    [<DataRow("01b", "def pred T(x:obj) {x}", 0)>]
    [<DataRow("01c", "def pred T(x:obj) {y}", 1)>]
    [<DataRow("01d", "def pred T() {dec x:obj; true}", 1)>]
    [<DataRow("01e", "def pred T() {dec x:obj; x}", 0)>]
    [<DataRow("01f", "def pred T() {dec x:obj; y}", 1)>]
    [<DataRow("02", "def func T(x:obj)->obj {return xy}", 1)>]
    [<DataRow("02a", "def func T(x:obj)->obj {intr}", 0)>]
    [<DataRow("02b", "def func T(x:obj)->obj {return x}", 0)>]
    [<DataRow("02c", "def func T()->obj {dec x:obj; return xy}", 1)>]
    [<DataRow("02d", "def func T()->obj {dec x:obj; return x}", 0)>]
    [<DataRow("03", "def cl T {dec x:obj; ctor T() {}}", 1)>]
    [<DataRow("03a", "def cl T {dec x:obj; ctor T() {dec x:=x; }}", 0)>]
    [<DataRow("03b", "def cl T {dec x:obj; ctor T() {dec y:=y; }}", 1)>]
    [<DataRow("04", "thm T {dec x:obj; true}", 1)>]
    [<DataRow("04a", "thm T {dec x:obj; true} prf T$1 {1: x qed}", 1)>]
    [<DataRow("04b", "thm T {dec x:obj; true} prf T$1 {1: trivial qed}", 1)>]
    [<DataRow("04c", "thm T {dec x:obj; x}", 0)>]
    [<DataRow("04d", "thm T {dec x:pred; x}", 0)>]
    [<DataRow("04e", "thm T {dec x:obj; y}", 1)>]
    [<DataRow("04f", "thm T {dec x:pred; y}", 1)>]
    [<DataRow("05", "prop T {dec x:obj; true}", 1)>]
    [<DataRow("05a", "prop T {dec x:obj; true} prf T$1 {1: x qed}", 1)>]
    [<DataRow("05b", "prop T {dec x:obj; true} prf T$1 {1: trivial qed}", 1)>]
    [<DataRow("05c", "prop T {dec x:obj; x}", 0)>]
    [<DataRow("05d", "prop T {dec x:pred; x}", 0)>]
    [<DataRow("05e", "prop T {dec x:obj; y}", 1)>]
    [<DataRow("05f", "prop T {dec x:pred; y}", 1)>]
    [<DataRow("06", "lem T {dec x:obj; true}", 1)>]
    [<DataRow("06a", "lem T {dec x:obj; true} prf T$1 {1: x qed}", 1)>]
    [<DataRow("06b", "lem T {dec x:obj; true} prf T$1 {1: trivial qed}", 1)>]
    [<DataRow("06c", "lem T {dec x:obj; x}", 0)>]
    [<DataRow("06d", "lem T {dec x:pred; x}", 0)>]
    [<DataRow("06e", "lem T {dec x:obj; y}", 1)>]
    [<DataRow("06f", "lem T {dec x:pred; y}", 1)>]
    [<DataRow("06", "ax T {dec x:obj; true}", 1)>]
    [<DataRow("06a", "ax T {dec x:obj; x}", 0)>]
    [<DataRow("06b", "ax T {dec x:pred; x}", 0)>]
    [<DataRow("06c", "ax T {dec x:obj; y}", 1)>]
    [<DataRow("06d", "ax T {dec x:pred; y}", 1)>]
    [<DataRow("07", "conj T {dec x:obj; true}", 1)>]
    [<DataRow("07a", "conj T {dec x:obj; x}", 0)>]
    [<DataRow("07b", "conj T {dec x:pred; x}", 0)>]
    [<DataRow("07c", "conj T {dec x:obj; y}", 1)>]
    [<DataRow("07d", "conj T {dec x:pred; y}", 1)>]
    [<DataRow("08", "cor T$1 {dec x:obj; true}", 1)>]
    [<DataRow("08a", "cor T$1 {dec x:obj; true} prf T$1 {1: x qed}", 1)>]
    [<DataRow("08b", "cor T$1 {dec x:obj; true} prf T$1 {1: trivial qed}", 1)>]
    [<DataRow("08c", "cor T$1 {dec x:obj; x}", 0)>]
    [<DataRow("08d", "cor T$1 {dec x:pred; x}", 0)>]
    [<DataRow("08e", "cor T$1 {dec x:obj; y}", 1)>]
    [<DataRow("08f", "cor T$1 {dec x:pred; y}", 1)>]
    [<DataRow("09", "inf T {dec x:pred; pre: true con:true}", 1)>]
    [<DataRow("09a", "inf T {dec x:pred; pre: true con:x}", 0)>]
    [<DataRow("09b", "inf T {dec x:pred; pre: x con:true}", 0)>]
    [<DataRow("09c", "inf T {dec x:pred; pre: true con:y}", 1)>]
    [<DataRow("09d", "inf T {dec x:pred; pre: y con:true}", 1)>]
    [<DataRow("09e", "inf T {dec x:pred; pre: true con:true}", 1)>]
    [<DataRow("09f", "inf T {dec x:pred; pre: true con:x}", 0)>]
    [<DataRow("09g", "inf T {dec x:pred; pre: x con:true}", 0)>]
    [<DataRow("09h", "inf T {dec x:pred; pre: true con:y}", 1)>]
    [<DataRow("09i", "inf T {dec x:pred; pre: y con:true}", 1)>]
    [<DataRow("19", """loc iif(x, y) := !tex: x "\Leftrightarrow" y !eng: x " if and only if " y !ger: x " dann und nur dann wenn " y;""", 0)>]
    [<DataRow("19a", """loc iif(x, y) := !tex: x "\Leftrightarrow" !eng: x " if and only if " !ger: x " dann und nur dann wenn ";""", 3)>]
    [<DataRow("19b", """loc iif(x, y) := !tex: "\Leftrightarrow" !eng: " if and only if " !ger: " dann und nur dann wenn ";""", 6)>]
    [<DataRow("20", "def pred S() {intr prty pred T(x:obj) {intr}}", 0)>]
    [<DataRow("20a", "def pred S() {intr prty pred T(x:obj) {x}}", 0)>]
    [<DataRow("20b", "def pred S() {intr prty pred T(x:obj) {y}}", 1)>]
    [<DataRow("20c", "def pred S() {intr prty pred T() {dec x:obj; true}}", 1)>]
    [<DataRow("20d", "def pred S() {intr prty pred T() {dec x:obj; x}}", 0)>]
    [<DataRow("20e", "def pred S() {intr prty pred T() {dec x:obj; y}}", 1)>]
    [<DataRow("21", "def pred S() {intr prty func T(x:obj)->obj {return xy}}", 1)>]
    [<DataRow("21a", "def pred S() {intr prty func T(x:obj)->obj {intr}}", 0)>]
    [<DataRow("21b", "def pred S() {intr prty func T(x:obj)->obj {return x}}", 0)>]
    [<DataRow("21c", "def pred S() {intr prty func T()->obj {dec x:obj; return xy}}", 1)>]
    [<DataRow("21d", "def pred S() {intr prty func T()->obj {dec x:obj; return x}}", 0)>]
    [<DataRow("22", "axiom T {dec p:pred(n:obj); all n:Nat{p(n)} }", 0)>]
    [<DataRow("23", "axiom T {dec p:pred(n:obj); p(@0)}", 0)>]
    [<DataRow("24a", "def cl A {dec myX:obj; ctor A(x:obj) {dec myX:=x;}}", 0)>]    
    [<DataRow("24b", "def cl A {dec myX:obj; ctor A(x:obj) {dec myX:=x;}} def cl B:A { ctor B() {dec base.A(@1); } }", 0)>]
    [<DataRow("25", "def func Sum(list:*Nat[ind])->Nat {dec result, addend: Nat result:=Zero() for addend in list { result:=Add(result,addend) } ; return result}", 0)>]
    [<DataRow("99", "uses Fpl.Commons.Structures ", 0)>]
    [<TestMethod>]
    member this.TestVAR04(no:string, fplCode:string, expected) =
        if offlineWatcher.OfflineMode && fplCode.StartsWith("uses Fpl.") then 
            ()
        else
            let code = VAR04 ""
            runTestHelper "TestVAR04.fpl" fplCode code expected
