namespace Diagnostics.VariableRelated

open Microsoft.VisualStudio.TestTools.UnitTesting
open Fpl.Errors.Diagnostics
open Fpl.Interpreter.Helpers.Debug
open TestFplInterpreter.Helpers.Common

(* VAR03
   Purpose: Detect duplicate variable declarations inside the same scope.
   What it indicates: The same identifier is declared multiple times in one scope, creating ambiguity about which declaration is referenced.
   Use: Surface naming collisions so the author can decide which declaration is intended or rename one occurrence.
   Action / Treat: Remove or rename the redundant declaration to ensure a single clear binding; treat VAR03 as an error that prevents unambiguous name resolution. *)

[<TestClass>]
type TestVAR03() =

    // simple blocks
    [<DataRow("00", "def pred Test(x,x:* pred[ind]) {true}", 1)>]
    [<DataRow("00a", "def pred Test(x,x:* pred[obj]) {true}", 1)>]
    [<DataRow("00b", "def pred Test(x,x: pred) {true}", 1)>]
    [<DataRow("00c", "def pred Test(x: pred) {true}", 0)>]
    [<DataRow("00d", "def pred Test(x:* pred[ind]) {dec x:obj; true}", 1)>]
    [<DataRow("00_1", "def func Test(x,x:* pred[ind])->obj {intr}", 1)>]
    [<DataRow("00a_1", "def func Test(x,x:* pred[obj])->obj {intr}", 1)>]
    [<DataRow("00b_1", "def func Test(x,x: pred)->obj {intr}", 1)>]
    [<DataRow("00c_1", "def func Test(x: pred)->obj {intr}", 0)>]
    [<DataRow("00d_1", "def func Test(x:* pred[ind])->obj {dec x:obj; return x}", 1)>]
    [<DataRow("00_2", "def cl Test {dec x,x:* pred[ind]; ctor Test(){}}", 1)>]
    [<DataRow("00a_2", "def cl Test {dec x,x:* pred[obj]; ctor Test(){}}", 1)>]
    [<DataRow("00b_2", "def cl Test {dec x,x: pred; ctor Test(){}}", 1)>]
    [<DataRow("00c_2", "def cl Test {dec x: pred; ctor Test(){}}", 0)>]
    [<DataRow("00_3", "ax Test {dec x,x:* pred[ind]; true}", 1)>]
    [<DataRow("00a_3", "ax Test{dec x,x:* pred[obj]; true}", 1)>]
    [<DataRow("00b_3", "ax Test{dec x,x: pred; true}", 1)>]
    [<DataRow("00c_3", "ax Test{dec x: pred; true}", 0)>]
    [<DataRow("00_4", "thm Test {dec x,x:* pred[ind]; true}", 1)>]
    [<DataRow("00a_4", "thm Test{dec x,x:* pred[obj]; true}", 1)>]
    [<DataRow("00b_4", "thm Test{dec x,x: pred; true}", 1)>]
    [<DataRow("00c_4", "thm Test{dec x: pred; true}", 0)>]
    [<DataRow("00_5", "lem Test {dec x,x:* pred[ind]; true}", 1)>]
    [<DataRow("00a_5", "lem Test{dec x,x:* pred[obj]; true}", 1)>]
    [<DataRow("00b_5", "lem Test{dec x,x: pred; true}", 1)>]
    [<DataRow("00c_5", "lem Test{dec x: pred; true}", 0)>]
    [<DataRow("00_6", "prop Test {dec x,x:* pred[ind]; true}", 1)>]
    [<DataRow("00a_6", "prop Test{dec x,x:* pred[obj]; true}", 1)>]
    [<DataRow("00b_6", "prop Test{dec x,x: pred; true}", 1)>]
    [<DataRow("00c_6", "prop Test{dec x: pred; true}", 0)>]
    [<DataRow("00_7", "conj Test {dec x,x:* pred[ind]; true}", 1)>]
    [<DataRow("00a_7", "conj Test{dec x,x:* pred[obj]; true}", 1)>]
    [<DataRow("00b_7", "conj Test{dec x,x: pred; true}", 1)>]
    [<DataRow("00c_7", "conj Test{dec x: pred; true}", 0)>]
    [<DataRow("00_8", "inf Test {dec x,x:* pred[ind]; pre: true con:true}", 1)>]
    [<DataRow("00a_8", "inf Test {dec x,x:* pred[obj]; pre: true con:true}", 1)>]
    [<DataRow("00b_8", "inf Test {dec x,x: pred; pre: true con:true}", 1)>]
    [<DataRow("00c_8", "inf Test {dec x: pred; pre: true con:true}", 0)>]

    // properties
    [<DataRow("01a_0", "def pred Test() {true prty pred X(x,x:* pred[ind]) {true} }", 1)>]
    [<DataRow("01b_0", "def pred Test() {true prty pred X(x,x:* pred[obj]) {true} }", 1)>]
    [<DataRow("01c_0", "def pred Test() {true prty pred X(x,x: pred) {true} }", 1)>]
    [<DataRow("01d_0", "def pred Test() {true prty pred X(x: pred) {true} }", 0)>]
    [<DataRow("01e_0", "def pred Test(x:ind) {true prty pred X(x: pred) {true} }", 1)>]
    [<DataRow("01f_0", "def pred Test() {dec x:ind; true prty pred X(x: pred) {true} }", 1)>]
    [<DataRow("01a_1", "def pred Test() {true prty func X(x,x:* pred[ind])->obj {intr} }", 1)>]
    [<DataRow("01b_1", "def pred Test() {true prty func X(x,x:* pred[obj])->obj {intr} }", 1)>]
    [<DataRow("01c_1", "def pred Test() {true prty func X(x,x: pred)->obj {intr} }", 1)>]
    [<DataRow("01d_1", "def pred Test() {true prty func X(x: pred)->obj {intr} }", 0)>]
    [<DataRow("01e_1", "def pred Test(x:ind) {true prty func X(x: pred)->obj {intr} }", 1)>]
    [<DataRow("01f_1", "def pred Test() {dec x:ind; true prty pred X(x: pred) {intr} }", 1)>]
    [<DataRow("01a_2", "def pred Test() {true prty pred X(x,x:* pred[ind]) {true} }", 1)>]
    [<DataRow("01b_2", "def pred Test() {true prty pred X(x,x:* pred[obj]) {true} }", 1)>]
    [<DataRow("01c_2", "def pred Test() {true prty pred X(x,x: pred) {true} }", 1)>]
    [<DataRow("01d_2", "def pred Test() {true prty pred X(x: pred) {true} }", 0)>]
    [<DataRow("01e_2", "def pred Test(x:ind) {true prty pred X(x: pred) {true} }", 1)>]
    [<DataRow("01f_2", "def pred Test() {dec x:ind; true prty pred X(x: pred) {true} }", 1)>]
    [<DataRow("01a_3", "def pred Test() {true prty func X(x,x:* pred[ind])->obj {intr} }", 1)>]
    [<DataRow("01b_3", "def pred Test() {true prty func X(x,x:* pred[obj])->obj {intr} }", 1)>]
    [<DataRow("01c_3", "def pred Test() {true prty func X(x,x: pred)->obj {intr} }", 1)>]
    [<DataRow("01d_3", "def pred Test() {true prty func X(x: pred)->obj {intr} }", 0)>]
    [<DataRow("01e_3", "def pred Test(x:ind) {true prty func X(x: pred)->obj {intr} }", 1)>]
    [<DataRow("01f_3", "def pred Test() {dec x:ind; true prty pred X(x: pred) {intr} }", 1)>]

    // proofs or corollaries
    [<DataRow("02a_0", "theorem TestId {dec x:ind; true}       proof       TestId$1 { dec x:obj; 1: trivial }", 1)>]
    [<DataRow("02b_0", "theorem TestId {dec x: ind; true}      proof       TestId$1 { 1: trivial }", 0)>]
    [<DataRow("02c_0", "theorem TestId {dec x:ind; true}       proof       TestId$1 { 1: trivial }", 0)>]
    [<DataRow("02d_0", "theorem TestId {dec x: ind; true}      corollary   TestId$1 { dec x:obj; true }", 1)>]
    [<DataRow("02e_0", "theorem TestId {dec x:ind; true}       corollary   TestId$1 { dec x:obj; true }", 1)>]
    [<DataRow("02f_0", "theorem TestId {dec x: ind; true}      corollary   TestId$1 { true }", 0)>]
    [<DataRow("02g_0", "theorem TestId {dec x:ind; true}       corollary   TestId$1 { true }", 0)>]
    [<DataRow("02h_0", "theorem TestId {dec x: ind; true}      corollary   TestId$1 {dec x:obj; true }", 1)>]
    [<DataRow("02i_0", "theorem TestId {dec x: ind; true}      corollary   TestId$1 { true }   proof       TestId$1$1 { dec x:obj; 1: trivial } ", 1)>]
    [<DataRow("02j_0", "theorem TestId {dec x: ind; true}      corollary   TestId$1 { true }   corollary   TestId$1$1 { dec x:obj; true } ", 1)>]
    [<DataRow("02k_0", "theorem TestId {dec x: ind; true}      corollary   TestId$1 { true }   corollary   TestId$1$1 {dec x:obj; true } ", 1)>]
    [<DataRow("02l_0", "theorem TestId {dec x:ind; true}       corollary   TestId$1 {dec x:obj; true }", 1)>]
    [<DataRow("02m_0", "theorem TestId {dec x: ind; true}      corollary   TestId$1 { true }", 0)>]
    [<DataRow("02n_0", "theorem TestId {dec x:ind; true}       corollary   TestId$1 { true }", 0)>]
    [<DataRow("02o_0", "theorem TestId {dec x: ind; true}      proof       TestId$1 { dec x:obj; 1: trivial }", 1)>]
    [<DataRow("02a_1", "lemma TestId {dec x:ind; true}         proof       TestId$1 { dec x:obj; 1: trivial }", 1)>]
    [<DataRow("02b_1", "lemma TestId {dec x: ind; true}        proof       TestId$1 { 1: trivial }", 0)>]
    [<DataRow("02c_1", "lemma TestId {dec x:ind; true}         proof       TestId$1 { 1: trivial }", 0)>]
    [<DataRow("02d_1", "lemma TestId {dec x: ind; true}        corollary   TestId$1 { dec x:obj; true }", 1)>]
    [<DataRow("02e_1", "lemma TestId {dec x:ind; true}         corollary   TestId$1 { dec x:obj; true }", 1)>]
    [<DataRow("02f_1", "lemma TestId {dec x: ind; true}        corollary   TestId$1 { true }", 0)>]
    [<DataRow("02g_1", "lemma TestId {dec x:ind; true}         corollary   TestId$1 { true }", 0)>]
    [<DataRow("02h_1", "lemma TestId {dec x: ind; true}        corollary   TestId$1 {dec x:obj; true }", 1)>]
    [<DataRow("02i_1", "lemma TestId {dec x: ind; true}        corollary   TestId$1 { true }   proof       TestId$1$1 { dec x:obj; 1: trivial } ", 1)>]
    [<DataRow("02j_1", "lemma TestId {dec x: ind; true}        corollary   TestId$1 { true }   corollary   TestId$1$1 { dec x:obj; true } ", 1)>]
    [<DataRow("02k_1", "lemma TestId {dec x: ind; true}        corollary   TestId$1 { true }   corollary   TestId$1$1 {dec x:obj; true } ", 1)>]
    [<DataRow("02l_1", "lemma TestId {dec x:ind; true}         corollary   TestId$1 {dec x:obj; true }", 1)>]
    [<DataRow("02m_1", "lemma TestId {dec x: ind; true}        corollary   TestId$1 { true }", 0)>]
    [<DataRow("02n_1", "lemma TestId {dec x:ind; true}         corollary   TestId$1 { true }", 0)>]
    [<DataRow("02o_1", "lemma TestId {dec x: ind; true}        proof       TestId$1 { dec x:obj; 1: trivial }", 1)>]
    [<DataRow("02a_2", "proposition TestId {dec x:ind; true}   proof       TestId$1 { dec x:obj; 1: trivial }", 1)>]
    [<DataRow("02b_2", "proposition TestId {dec x: ind; true}  proof       TestId$1 { 1: trivial }", 0)>]
    [<DataRow("02c_2", "proposition TestId {dec x:ind; true}   proof       TestId$1 { 1: trivial }", 0)>]
    [<DataRow("02d_2", "proposition TestId {dec x: ind; true}  corollary   TestId$1 { dec x:obj; true }", 1)>]
    [<DataRow("02e_2", "proposition TestId {dec x:ind; true}   corollary   TestId$1 { dec x:obj; true }", 1)>]
    [<DataRow("02f_2", "proposition TestId {dec x: ind; true}  corollary   TestId$1 { true }", 0)>]
    [<DataRow("02g_2", "proposition TestId {dec x:ind; true}   corollary   TestId$1 { true }", 0)>]
    [<DataRow("02h_2", "proposition TestId {dec x: ind; true}  corollary   TestId$1 {dec x:obj; true }", 1)>]
    [<DataRow("02i_2", "proposition TestId {dec x: ind; true}  corollary   TestId$1 { true }   proof       TestId$1$1 { dec x:obj; 1: trivial } ", 1)>]
    [<DataRow("02j_2", "proposition TestId {dec x: ind; true}  corollary   TestId$1 { true }   corollary   TestId$1$1 { dec x:obj; true } ", 1)>]
    [<DataRow("02k_2", "proposition TestId {dec x: ind; true}  corollary   TestId$1 { true }   corollary   TestId$1$1 {dec x:obj; true } ", 1)>]
    [<DataRow("02l_2", "proposition TestId {dec x:ind; true}   corollary   TestId$1 {dec x:obj; true }", 1)>]
    [<DataRow("02m_2", "proposition TestId {dec x: ind; true}  corollary   TestId$1 { true }", 0)>]
    [<DataRow("02n_2", "proposition TestId {dec x:ind; true}   corollary   TestId$1 { true }", 0)>]
    [<DataRow("02o_2", "proposition TestId {dec x: ind; true}  proof       TestId$1 { dec x:obj; 1: trivial }", 1)>]
    [<DataRow("02a_3", "corollary TestId$1 {dec x:ind; true}   proof       TestId$1$1 { dec x:obj; 1: trivial }", 1)>]
    [<DataRow("02b_3", "corollary TestId$1 {dec x: ind; true}  proof       TestId$1$1 { 1: trivial }", 0)>]
    [<DataRow("02c_3", "corollary TestId$1 {dec x:ind; true}   proof       TestId$1$1 { 1: trivial }", 0)>]
    [<DataRow("02d_3", "corollary TestId$1 {dec x: ind; true}  corollary   TestId$1$1 { dec x:obj; true }", 1)>]
    [<DataRow("02e_3", "corollary TestId$1 {dec x:ind; true}   corollary   TestId$1$1 { dec x:obj; true }", 1)>]
    [<DataRow("02f_3", "corollary TestId$1 {dec x: ind; true}  corollary   TestId$1$1 { true }", 0)>]
    [<DataRow("02g_3", "corollary TestId$1 {dec x:ind; true}   corollary   TestId$1$1 { true }", 0)>]
    [<DataRow("02h_3", "corollary TestId$1 {dec x: ind; true}  corollary   TestId$1$1 {dec x:obj; true }", 1)>]
    [<DataRow("02i_3", "corollary TestId$1 {dec x: ind; true}  corollary   TestId$1$1 { true } proof       TestId$1$1$1 { dec x:obj; 1: trivial } ", 1)>]
    [<DataRow("02j_3", "corollary TestId$1 {dec x: ind; true}  corollary   TestId$1$1 { true } corollary   TestId$1$1$1 { dec x:obj; true } ", 1)>]
    [<DataRow("02k_3", "corollary TestId$1 {dec x: ind; true}  corollary   TestId$1$1 { true } corollary   TestId$1$1$1 {dec x:obj; true } ", 1)>]
    [<DataRow("02l_3", "corollary TestId$1 {dec x:ind; true}   corollary   TestId$1$1 {dec x:obj; true }", 1)>]
    [<DataRow("02m_3", "corollary TestId$1 {dec x: ind; true}  corollary   TestId$1$1 { true }", 0)>]
    [<DataRow("02n_3", "corollary TestId$1 {dec x:ind; true}   corollary   TestId$1$1 { true }", 0)>]
    [<DataRow("02o_3", "corollary TestId$1 {dec x: ind; true}  proof       TestId$1$1 { dec x:obj; 1: trivial }", 1)>]
    
    [<DataRow("02d_4", "conjecture TestId  {dec x: ind; true}  corollary   TestId$1 { dec x:obj; true }", 1)>]
    [<DataRow("02e_4", "conjecture TestId  {dec x:ind; true}   corollary   TestId$1 { dec x:obj; true }", 1)>]
    [<DataRow("02f_4", "conjecture TestId  {dec x: ind; true}  corollary   TestId$1 { true }", 0)>]
    [<DataRow("02g_4", "conjecture TestId  {dec x:ind; true}   corollary   TestId$1 { true }", 0)>]
    [<DataRow("02h_4", "conjecture TestId  {dec x: ind; true}  corollary   TestId$1 {dec x:obj; true }", 1)>]
    [<DataRow("02i_4", "conjecture TestId  {dec x: ind; true}  corollary   TestId$1 { true } proof       TestId$1$1 { dec x:obj; 1: trivial } ", 1)>]
    [<DataRow("02j_4", "conjecture TestId  {dec x: ind; true}  corollary   TestId$1 { true } corollary   TestId$1$1 { dec x:obj; true } ", 1)>]
    [<DataRow("02k_4", "conjecture TestId  {dec x: ind; true}  corollary   TestId$1 { true } corollary   TestId$1$1 {dec x:obj; true } ", 1)>]
    [<DataRow("02l_4", "conjecture TestId  {dec x:ind; true}   corollary   TestId$1 {dec x:obj; true }", 1)>]
    [<DataRow("02m_4", "conjecture TestId  {dec x: ind; true}  corollary   TestId$1 { true }", 0)>]
    [<DataRow("02n_4", "conjecture TestId  {dec x:ind; true}   corollary   TestId$1 { true }", 0)>]

    [<DataRow("02d_5", "axiom      TestId  {dec x: ind; true}  corollary   TestId$1 { dec x:obj; true }", 1)>]
    [<DataRow("02e_5", "axiom      TestId  {dec x:ind; true}   corollary   TestId$1 { dec x:obj; true }", 1)>]
    [<DataRow("02f_5", "axiom      TestId  {dec x: ind; true}  corollary   TestId$1 { true }", 0)>]
    [<DataRow("02g_5", "axiom      TestId  {dec x:ind; true}   corollary   TestId$1 { true }", 0)>]
    [<DataRow("02h_5", "axiom      TestId  {dec x: ind; true}  corollary   TestId$1 {dec x:obj; true }", 1)>]
    [<DataRow("02i_5", "axiom      TestId  {dec x: ind; true}  corollary   TestId$1 { true } proof       TestId$1$1 { dec x:obj; 1: trivial } ", 1)>]
    [<DataRow("02j_5", "axiom      TestId  {dec x: ind; true}  corollary   TestId$1 { true } corollary   TestId$1$1 { dec x:obj; true } ", 1)>]
    [<DataRow("02k_5", "axiom      TestId  {dec x: ind; true}  corollary   TestId$1 { true } corollary   TestId$1$1 {dec x:obj; true } ", 1)>]
    [<DataRow("02l_5", "axiom      TestId  {dec x:ind; true}   corollary   TestId$1 {dec x:obj; true }", 1)>]
    [<DataRow("02m_5", "axiom      TestId  {dec x: ind; true}  corollary   TestId$1 { true }", 0)>]
    [<DataRow("02n_5", "axiom      TestId  {dec x:ind; true}   corollary   TestId$1 { true }", 0)>]

    [<DataRow("03a", "ext Digits x@/\d+/ -> Nat {dec n:Nat; return n}", 0)>]
    [<DataRow("03b", "ext Digits x@/\d+/ -> Nat {dec x:Nat; return x}", 1)>]
    [<DataRow("03c", "ext Digits x@/\d+/ -> Nat {dec x:*obj[ind]; return x}", 1)>]
    [<DataRow("03d", "ext Digits x@/\d+/ -> Nat {dec x:*ind[ind]; return x}", 1)>]

    [<DataRow("04", "inf ModusPonens {dec p,q: pred; pre: and (p, impl (p,q) ) con: q}", 0)>]
    [<DataRow("05", "def pred Test() {true prty pred X(y:* pred[ind]) {dec x:obj; ex x:obj {true}} }", 1)>]
    [<DataRow("06", "def pred Test() {true prty pred X(y:* pred[ind]) {ex x:obj {true}} }", 0)>]
    [<DataRow("07", "def pred Test() {true prty func X(y:* pred[ind])->obj {dec x:obj; return x} }", 0)>]
    [<DataRow("09", "def pred Test(x: ind) {true prty pred X(x: pred) {true} }", 1)>]
    [<DataRow("09a", "def pred Test(x: ind) {true prty pred X(x:* pred[ind]) {true} }", 1)>]
    [<DataRow("09b", "def pred Test(x: ind) {true prty pred X(x:* pred[obj]) {true} }", 1)>]
    [<DataRow("09c", "def pred Test(x: ind) {true prty pred X() {dec x: obj; true} }", 1)>]
    [<DataRow("09d", "def pred Test(x: ind) {true prty pred X() {dec x:* obj[ind]; true} }", 1)>]
    [<DataRow("09e", "def pred Test(x: ind) {true prty pred X() {dec x:* obj[obj]; true} }", 1)>]
    [<DataRow("09f", "def pred Test(x: ind) {true prty func X(x: pred)->obj {intr} }", 1)>]
    [<DataRow("09g", "def pred Test(x: ind) {true prty func X(x:* pred[ind])->obj {intr} }", 1)>]
    [<DataRow("09h", "def pred Test(x: ind) {true prty func X(x:* pred[obj])->obj {intr} }", 1)>]
    [<DataRow("09i", "def pred Test(x: ind) {true prty func X()->obj {dec x: obj; return x} }", 1)>]
    [<DataRow("09j", "def pred Test(x: ind) {true prty func X()->obj {dec x:* obj[ind]; return x} }", 1)>]
    [<DataRow("09k", "def pred Test(x: ind) {true prty func X()->obj {dec x:* obj[obj]; return x} }", 1)>]
    [<DataRow("10", "def cl Test {dec x:ind; ctor Test(x: pred) {} }", 1)>]
    [<DataRow("10a", "def cl Test {dec x:ind; ctor Test(x:* pred[ind]) {} }", 1)>]
    [<DataRow("10b", "def cl Test {dec x:ind; ctor Test(x:* pred[ind]) {} }", 1)>]
    [<DataRow("10c", "def cl Test {dec x:ind; ctor Test() {dec x: obj; } }", 1)>]
    [<DataRow("10d", "def cl Test {dec x:ind; ctor Test() {dec x:* obj[ind]; } }", 1)>]
    [<DataRow("10e", "def cl Test {dec x:ind; ctor Test() {dec x:* obj[obj]; } }", 1)>]
    [<DataRow("11", "def cl Test {dec x:obj; constructor Test() {} prty func X(x: pred)->obj {intr} }", 1)>]
    [<DataRow("11a", "def cl Test {dec x:obj; constructor Test(x: pred) {} prty func X()->obj {intr} }", 1)>]
    [<DataRow("11b", "def cl Test {dec x:obj; constructor Test() {dec x: pred; } prty func X()->obj {intr} }", 1)>]
    [<DataRow("11c", "def cl Test {dec x:obj; constructor Test() {} prty func X()->obj {dec x: pred; return x} }", 1)>]
    [<DataRow("12", "inf ExistsByExample {dec p: pred(c: obj) x: obj; pre: p(c) con: ex x:obj {p(x)}}", 1)>]
    [<DataRow("12a", "inf ExistsByExample {dec p: pred(c: obj); pre: p(c) con: ex x:obj {p(x)}}", 0)>]
    [<DataRow("12b", "inf ExistsByExample {dec p: pred(c: obj) c: obj; pre: true con: true}", 1)>]
    [<DataRow("13", """loc and(p,q) := !tex: p "\wedge" q;""", 0)>]
    [<DataRow("14", """def cl B {intr} def cl A {dec x:obj; ctor A(x:B) {} }""", 1)>]
    [<DataRow("15", "axiom T {dec p:pred(n:obj); all n:Nat{p(n)} }", 1)>]
    [<DataRow("15a", "axiom T {dec p:pred(n:obj); all n1:Nat{p(n1)} }", 0)>]
    [<DataRow("16", "prop T { all x:obj {true} } proof T$1 { 1: all x:obj {true} }", 0)>]
    [<DataRow("99", "uses Fpl.Commons.Structures ", 0)>]
    [<TestMethod>]
    member this.TestVAR03(no: string, fplCode:string, expected) =
        if offlineWatcher.OfflineMode && fplCode.StartsWith("uses Fpl.") then 
            ()
        else
            let code = VAR03 ("", "")
            runTestHelper "TestVAR03.fpl" fplCode code expected
