<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.2" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
        <PackageReference Include="MSTest" Version="4.3.3" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="SpecialPurpose\TestWhitespaceControl.fs" />
        <Compile Include="LowLevel\TestVariableTypes.fs" />
        <Compile Include="LowLevel\TestProofRelated.fs" />
        <Compile Include="LowLevel\TestStatements.fs" />
        <Compile Include="LowLevel\TestPredicatesSpecific.fs" />
        <Compile Include="LowLevel\TestFunctionalTermProperty.fs" />
        <Compile Include="LowLevel\TestPredicateProperty.fs" />
        <Compile Include="LowLevel\TestConstructor.fs" />
        <Compile Include="LowLevel\TestPredicateWithQualification.fs" />
        <Compile Include="LowLevel\TestLocalizationElements.fs" />
        <Compile Include="LowLevel\TestIdentifiers.fs" />
        <Compile Include="LowLevel\TestSignatures.fs" />
        <Compile Include="LowLevel\TestCoordPossibilities.fs" />
        <Compile Include="LowLevel\TestClassInheritanceTypes.fs" />
        <Compile Include="LowLevel\TestExpression.fs" />
        <Compile Include="BuildingBlocks\TestReferenceRules.fs" />
        <Compile Include="BuildingBlocks\TestProof.fs" />
        <Compile Include="BuildingBlocks\TestTheoremLikeStatements.fs" />
        <Compile Include="BuildingBlocks\TestLocalization.fs" />
        <Compile Include="BuildingBlocks\TestDefinitionClass.fs" />
        <Compile Include="BuildingBlocks\TestDefinitionPredicate.fs" />
        <Compile Include="BuildingBlocks\TestDefinitionFunctionalTerm.fs" />
        <Compile Include="BuildingBlocks\TestExtension.fs" />
        <Compile Include="BuildingBlocks\TestUsesClause.fs" />
        <Compile Include="BuildingBlocks\TestAxioms.fs" />
        <Compile Include="TopLevel\TestDifferse.fs" />
        <Compile Include="MSTestSettings.fs" />
        <Compile Include="ErrRecovery\TestErrDiagnosticsLowLevel.fs" />
        <Compile Include="ErrRecovery\TestRecovery.fs" />
        <Compile Include="LSRelated\PrettyPrint\Commons.fs" />
        <Compile Include="LSRelated\PrettyPrint\TestExpressions.fs" />
        <Compile Include="LSRelated\PrettyPrint\TestDefinitionClass.fs" />
        <Compile Include="LSRelated\PrettyPrint\TestDefinitionFunctionalTerm.fs" />
    </ItemGroup>


    <ItemGroup>
        <ProjectReference Include="..\Fpl1Parser\Fpl1Parser.fsproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Update="FSharp.Core" Version="10.1.301" />
    </ItemGroup>


</Project>
