namespace TestFpl1Parser.LowLevel

open FParsec
open Fpl1Parser.Grammar
open Fpl0Base.Primitives
open Microsoft.VisualStudio.TestTools.UnitTesting


[<TestClass>]
type TestExpression () =

    [<DataRow("00", "(x = y * z + 1)")>]
    [<DataRow("01", "(x + 1)")>]
    [<DataRow("01a", "( x + 1)")>]
    [<DataRow("01b", "(x + 1 )")>]
    [<DataRow("02", "(1 + x)")>]
    [<DataRow("a01", "1")>]
    [<DataRow("a01", "f()")>]
    [<DataRow("a02", "x ∧ y")>]
    [<DataRow("a03", "false ∧ true")>]
    [<DataRow("a01d", "-false")>]
    [<DataRow("a01e", "false'")>]
    [<DataRow("a02d", "-and(a,b)")>]
    [<DataRow("a02e", "and(a,b)'")>]
    [<DataRow("a03d", "-mcases ( | true: true ? false )")>]
    [<DataRow("a03e", "mcases ( | true: true ? false )'")>]
    [<DataRow("00", """PrecedingResults1(x,y)""")>]
    [<DataRow("01", """x + y""")>]
    [<DataRow("02", """(x) + y""")>]
    [<DataRow("03", """(x) + (PrecedingResults1(x,y))""")>]
    [<DataRow("04", """z * (x) + y""")>]
    [<DataRow("04a", """z * (x + y)""")>]
    [<DataRow("05", """z / (x) + y""")>]
    [<DataRow("06", """z / (x - x) + y""")>]
    [<DataRow("07", """¬f ⇒ ¬g""")>]
    [<DataRow("07a", """(¬f ⇒ ¬g)""")>]
    [<DataRow("07b", """(¬f) ⇒ (¬g)""")>]
    [<DataRow("07c", """¬f ⇒ a""")>]
    [<DataRow("07d", """f ⇒ a""")>]
    [<DataRow("07e", """¬(f ⇒ a)""")>]
    [<DataRow("08", """all x:obj {not x}""")>]
    [<DataRow("09", """not x""")>]
    [<DataRow("09a", """¬ x""")>]
    [<DataRow("10a", """x!""")>]
    [<DataRow("10b", """x!!""")>]
    [<DataRow("10c", """(x!)!""")>]
    [<DataRow("11a", """~x""")>]
    [<DataRow("11b", """~~x""")>]
    [<DataRow("11c", """~(~x)""")>]
    [<DataRow("12", """Fact((Fact(a)))""")>]
    [<DataRow("13", """Zero()""")>]
    [<DataRow("14", """self(i)""")>]
    [<DataRow("15", """xor ( xor ( true, xor( true, false)), true )""")>]
    [<DataRow("16", """xor ( true, xor( true, false))""")>]
    [<DataRow("17", """xor ( true, true )""")>]
    [<DataRow("18", """iif ( iif ( true, iif( true, false)), true )""")>]
    [<DataRow("19", """iif ( true, iif( true, false))""")>]
    [<DataRow("20", """iif ( true, true )""")>]
    [<DataRow("21", """iif(true,false)""")>]
    [<DataRow("22", """impl ( impl ( true, impl( true, false)), true )""")>]
    [<DataRow("23", """impl ( true, impl( true, false))""")>]
    [<DataRow("24", """impl ( true, true )""")>]
    [<DataRow("25", """impl(true,false)""")>]
    [<DataRow("26", """or(x.z,y)""")>]
    [<DataRow("27", """or ( or ( true, or( true, false)), true )""")>]
    [<DataRow("28", """or ( true, or( true, false))""")>]
    [<DataRow("29", """or ( true, true )""")>]
    [<DataRow("30", """or(true,false)""")>]
    [<DataRow("31", """and ( and ( true, and( true, false)), true )""")>]
    [<DataRow("32", """and ( true, and( true, false))""")>]
    [<DataRow("33", """and ( true, true )""")>]
    [<DataRow("34", """and(true,false)""")>]
    [<DataRow("35", LiteralUndef)>]
    [<DataRow("36", LiteralFalse)>]
    [<DataRow("37", LiteralTrue)>]
    [<DataRow("38", """myOp.NeutralElement()""")>]
    [<DataRow("39", """myOp.NeutralElement().SomeProperty()""")>]
    [<DataRow("40", """not true""")>]
    [<DataRow("41", """not (iif ( true, not false))""")>]
    [<DataRow("42", """not (iif ( iif( true, false), true))""")>]
    [<DataRow("43", """not iif ( iif ( true, iif( true, false)), not true )""")>]
    [<DataRow("44", """is(x, Nat)""")>]
    [<DataRow("45", """all x,y,z:obj{true}""")>]
    [<DataRow("46", """all x,y,z:obj {not (iif ( true, not false))}""")>]
    [<DataRow("47", """all x,y,z:obj {not (iif ( iif( true, false), true))}""")>]
    [<DataRow("48", """all x:obj {not (iif ( iif ( true, iif( true, false)), not true ))}""")>]
    [<DataRow("49", """ex x,y,z:obj {true }""")>]
    [<DataRow("50", """ex x,y,z:obj { not (iif ( true, not false))}""")>]
    [<DataRow("51", """ex x,y,z:N {not (iif ( iif( true, false), true))}""")>]
    [<DataRow("52", """ex x:G {not (iif ( iif ( true, iif( true, false)), not true ))}""")>]
    [<DataRow("53", """exn$1 x:Nat {not (iif ( true, not (false)))}""")>]
    [<DataRow("54", """exn$2 x: Nat,y:B {not (iif ( iif( true, false), true))}""")>]
    [<DataRow("55", """exn$3 x:Is {not (iif ( iif ( true, iif( true, false)), not true ))}""")>]
    [<DataRow("56", """all arg:Args { is(arg,Set) }""")>]
    [<DataRow("57", """delegate.Abc(x,y,z)""")>]
    [<DataRow("58", """(z = y)""")>]
    [<DataRow("59", """(z @= true)""")>]
    [<DataRow("60", """(z @ true @= and(x,y))""")>]
    [<DataRow("61", """all x:Range, y:C, z:obj {and (and(a,b),c)}""")>]
    [<DataRow("62", """all x:Real, y:pred, z:func {and (and (a,b),c)}""")>]
    [<DataRow("63", """ex x:Range, y:C, z:obj {and (a,and( b,c))}""")>]
    [<DataRow("64", """ex x:Real, y:pred, z:func {and (a,and(b,c))}""")>]
    [<DataRow("65", """not (((x + y)))""")>]
    [<DataRow("66", """impl(T,true)""")>]
    [<DataRow("67", """(x = 0)""")>]
    [<DataRow("68", """(x = 12)""")>]
    [<DataRow("69", """(x = @0)""")>]
    [<DataRow("70", """(x = @12)""")>]
    [<DataRow("71", """parent(x, y).3[a, b]""")>]
    [<DataRow("72", """not x""")>]
    [<DataRow("not00", "true")>]
    [<DataRow("not01", "not true")>]
    [<DataRow("not02", "¬true")>]
    [<DataRow("not03", "¬¬true")>]
    [<DataRow("not04", "¬¬¬true")>]
    [<DataRow("not05", "¬ ¬¬true")>]
    [<DataRow("not06", "¬ ¬ ¬true")>]
    [<DataRow("not07", "¬ ¬ ¬ true")>]
    [<DataRow("not02a", "¬(true)")>]
    [<DataRow("not03a", "¬¬(true)")>]
    [<DataRow("not04a", "¬(¬¬(true))")>]
    [<DataRow("not05a", "¬ (¬¬true)")>]
    [<DataRow("not06a", "¬ ¬ ¬(true)")>]
    [<DataRow("not07a", "¬ ¬ ¬ ( true)")>]
    [<DataRow("is00", "n ∈ N")>]
    [<DataRow("is01", "¬¬n ∈ N")>]
    [<DataRow("is02", "x ∈ N ∈ X")>]
    [<DataRow("is03", "is(n,N)")>]
    [<DataRow("is04", "¬¬is(n, N)")>]
    [<DataRow("is05", "is(is(x , N), X)")>]
    [<DataRow("is06", "is(x ∈ N, X)")>]
    [<DataRow("and00", "x ∧ y")>]
    [<DataRow("and01", "¬¬n ∧ x")>]
    [<DataRow("and02", "x ∧ y ∧ z")>]
    [<DataRow("and03", "∧(x,y)")>]
    [<DataRow("and04", "¬¬∧(x, y)")>]
    [<DataRow("and05", "∧(∧(x , y), z)")>]
    [<DataRow("and06", "∧(x ∧ y, z)")>]
    [<DataRow("and07", "and(a,b)")>]
    [<DataRow("or00", "x ∨ y")>]
    [<DataRow("or01", "¬¬n ∨ x")>]
    [<DataRow("or02", "x ∨ y ∨ z")>]
    [<DataRow("or03", "∨(x,y)")>]
    [<DataRow("or04", "¬¬∨(x, y)")>]
    [<DataRow("or05", "∨(∨(x , y), z)")>]
    [<DataRow("or06", "∨(x ∨ y, z)")>]
    [<DataRow("impl00", "x ⇒ y")>]
    [<DataRow("impl01", "¬¬n ⇒ x")>]
    [<DataRow("impl02", "x ⇒ y ⇒ z")>]
    [<DataRow("impl03", "⇒(x,y)")>]
    [<DataRow("impl04", "¬¬⇒(x, y)")>]
    [<DataRow("impl05", "⇒(⇒(x , y), z)")>]
    [<DataRow("impl06", "⇒(x ⇒ y, z)")>]
    [<DataRow("xor00", "x ⩡ y")>]
    [<DataRow("xor01", "¬¬n ⩡ x")>]
    [<DataRow("xor02", "x ⩡ y ⩡ z")>]
    [<DataRow("xor03", "⩡(x,y)")>]
    [<DataRow("xor04", "¬¬⩡(x, y)")>]
    [<DataRow("xor05", "⩡(⩡(x , y), z)")>]
    [<DataRow("xor06", "⩡(x ⩡ y, z)")>]
    [<DataRow("iif00", "x ⇔ y")>]
    [<DataRow("iif01", "¬¬n ⇔ x")>]
    [<DataRow("iif02", "x ⇔ y ⇔ z")>]
    [<DataRow("iif03", "⇔(x,y)")>]
    [<DataRow("iif04", "¬¬⇔(x, y)")>]
    [<DataRow("iif05", "⇔(⇔(x , y), z)")>]
    [<DataRow("iif06", "⇔(x ⇔ y, z)")>]
    [<DataRow("all00", "∀ m, n:Nat {((n') = (m'))}")>]
    [<DataRow("all01", "∀ m, n:Nat { true }")>]
    [<DataRow("all02", "∀ m:Nat { true }")>]
    [<DataRow("all03", "∀ m, n:Nat {((n') = (m')) ⇒ (n = m)}")>]
    [<DataRow("all04", "∀ m, n:Nat {((n') = (m')) ⇒ (n = m)}")>]
    [<DataRow("all05", "∀ n:Nat {true ⇔ false ⩡ (n ∈ N ⇔ true)}")>]
    [<DataRow("all06", "∀ n:Nat {true ⇔ false ∧ (n ∈ N ⇔ true)}")>]
    [<DataRow("all07", "∀ n:Nat {true ⇔ false ∨ (n ∈ N ⇔ true)}")>]
    [<DataRow("all08", "∀ n:Nat {true ⇔ false ⇒ (n ∈ N ⇔ true)}")>]
    [<DataRow("all09", "∀ n:Nat {true ⇔ false ⇔ (n ∈ N ⇔ true)}")>]
    [<DataRow("all10", "∀ n:Nat {¬(¬n ∈ N ∧ true ⩡ false)}")>]
    [<DataRow("all11", "∀ x, y:Set {x ∈ N ⇒ (x = y)}")>]
    [<DataRow("all12", "∀ x:obj {¬(x ∈ N ⇔ false)}")>]
    [<DataRow("all13", "∀ x:obj {¬true ⩡ false ⩡ (x ∈ N ⇒ false)}")>]
    [<DataRow("all14", "∀ x:obj {¬true ⩡ false ∧ (x ∈ N ⇒ false)}")>]
    [<DataRow("all15", "∀ x:obj {¬true ⩡ false ∨ (x ∈ N ⇒ false)}")>]
    [<DataRow("all16", "∀ x:obj {¬true ⩡ false ⇒ (x ∈ N ⇒ false)}")>]
    [<DataRow("all17", "∀ x:obj {¬true ⩡ false ⇔ (x ∈ N ⇒ false)}")>]
    [<DataRow("all18", "∀ x:obj {x ∈ N} ⩡ ∃ y:obj {y ∈ M}")>]
    [<DataRow("all19", "∀ x:obj {x ∈ N} ∧ (¬false ∨ ∃ y:obj {y ∈ M})")>]
    [<DataRow("all20", "∀ x:obj {x ∈ N} ∧ ∃ y:obj {y ∈ M}")>]
    [<DataRow("all21", "∀ x:obj {x ∈ N} ∧ ¬∃ y:obj {y ∈ M}")>]
    [<DataRow("all22", "∀ x:obj {x ∈ N} ∨ (¬false ∧ true ⩡ false)")>]
    [<DataRow("all23", "∀ x:obj {x ∈ N} ⇒ true ⩡ false")>]
    [<DataRow("all24", "∀ x:obj {x ∈ N} ⇒ ∃ y:obj {y ∈ M}")>]
    [<DataRow("all25", "∀ x:obj {x ∈ N} ⇔ ∃ y:obj {y ∈ M}")>]
    [<DataRow("all26", "∀ x:obj {x ∈ N}")>]
    [<DataRow("all27", "∀ y:obj {y ∈ K} ∧ ∃ n:Nat {n ∈ M ⩡ true}")>]
    [<DataRow("all28", "∀ y:obj {y ∈ M} ⩡ ∃ n:Nat {n ∈ K ⩡ true}")>]
    [<DataRow("all29", "∀ y:obj {y ∈ M} ∨ ∃ n:Nat {n ∈ K ⩡ true}")>]
    [<DataRow("all30", "∀ y:obj {y ∈ M} ⇒ ∀ n:Nat {n ∈ K ⩡ true}")>]
    [<DataRow("all31", "∀ y:obj {y ∈ M} ⇒ ∃ n:Nat {n ∈ K ⩡ true}")>]
    [<DataRow("all32", "∀ y:obj {y ∈ M} ⇔ ∀ n:Nat {n ∈ K ⩡ true}")>]
    [<DataRow("all33", "∀ y:obj {y ∈ M} ⇔ ∃ n:Nat {n ∈ K ⩡ true}")>]
    [<DataRow("all34", "∀ z:obj {∀ y:obj {y ∈ M} ⩡ (z ∈ K ⩡ true)}")>]
    [<DataRow("all35", "∀ z:obj {∀ y:obj {y ∈ M} ⇒ (z ∈ K ⩡ true)}")>]
    [<DataRow("all36", "∀ z:obj {∀ y:obj {y ∈ M} ⇔ (z ∈ K ⩡ true)}")>]
    [<DataRow("all37", "∀ z:obj {∃ y:obj {y ∈ M} ∧ (z ∈ K ⩡ true)}")>]
    [<DataRow("all38", "∀ z:obj {∃ y:obj {y ∈ M} ∨ (z ∈ K ⩡ true)}")>]
    [<DataRow("ex01", "∃ x:obj {(x ∈ Nat)}")>] 
    [<DataRow("ex02", "∃ m, n:Nat { true }")>]
    [<DataRow("ex03", "∃ x:obj {x ∈ N}")>]
    [<DataRow("ex04", "∃ a:obj {a ∈ N ⇔ true}")>]
    [<DataRow("ex05", "∃ n:Nat {true ⇔ false ⩡ (n ∈ N ⇔ true)}")>]
    [<DataRow("ex06", "∃ n:Nat {true ⇔ false ∧ (n ∈ N ⇔ true)}")>]
    [<DataRow("ex07", "∃ n:Nat {true ⇔ false ∨ (n ∈ N ⇔ true)}")>]
    [<DataRow("ex08", "∃ n:Nat {true ⇔ false ⇒ (n ∈ N ⇔ true)}")>]
    [<DataRow("ex09", "∃ n:Nat {true ⇔ false ⇔ (n ∈ N ⇔ true)}")>]
    [<DataRow("ex10", "∃ n:Nat {¬(n ∈ N ⇒ true ⩡ false)}")>]
    [<DataRow("ex11", "∃ n:obj {n ∈ N}")>]
    [<DataRow("ex12", "∃ x:obj {¬true ⩡ false ⩡ (x ∈ N ⇒ false)}")>]
    [<DataRow("ex13", "∃ x:obj {¬true ⩡ false ∧ (x ∈ N ⇒ false)}")>]
    [<DataRow("ex14", "∃ x:obj {¬true ⩡ false ∨ (x ∈ N ⇒ false)}")>]
    [<DataRow("ex15", "∃ x:obj {¬true ⩡ false ⇒ (x ∈ N ⇒ false)}")>]
    [<DataRow("ex16", "∃ x:obj {¬true ⩡ false ⇔ (x ∈ N ⇒ false)}")>]
    [<DataRow("ex17", "∃ x:obj {¬x ∈ N}")>]
    [<DataRow("ex18", "∃ x:obj {x ∈ N} ∧ (true ∨ false ∨ true ⩡ false)")>]
    [<DataRow("ex19", "∃ x:obj {x ∈ Nat}")>]
    [<DataRow("ex20", "∃ x:tpl {a ∈ M ∧ (a = $1)}")>]
    [<DataRow("ex21", "∃ x:tpl {∀ z:obj {z ∈ K} ⩡ ¬true ⩡ false}")>]
    [<DataRow("ex22", "∃ x:tpl {∃ x:obj {x ∈ M} ∧ true ⇔ false}")>]
    [<DataRow("ex23", "∃ x1:obj {¬(x1 ∈ N)}")>]
    [<DataRow("ex24", "∃ y:obj {∀ z:obj {z ∈ K} ∧ (y ∈ M ⩡ true)}")>]
    [<DataRow("ex25", "∃ y:obj {¬¬y ∈ M}")>]
    [<DataRow("ex26", "∃ y:obj {y ∈ K} ∧ ∀ n:Nat {n ∈ K ⩡ true}")>]
    [<DataRow("ex27", "∃ y:obj {y ∈ M} ∨ ∀ n:Nat {n ∈ K ⩡ true}")>]
    [<DataRow("ex28", "∃ y:obj {y ∈ M} ⇒ ∀ x:obj {x ∈ N}")>]
    [<DataRow("ex29", "∃ y:obj {y ∈ M}")>]
    [<DataRow("ex30", "∃ z:obj {∀ y:obj {y ∈ M} ⩡ (z ∈ K ⩡ true)}")>]
    [<DataRow("ex31", "∃ z:obj {∀ y:obj {y ∈ M} ∨ (z ∈ K ⩡ true)}")>]
    [<DataRow("ex32", "∃ z:obj {∀ y:obj {y ∈ M} ⇒ (z ∈ K ⩡ true)}")>]
    [<DataRow("ex33", "∃ z:obj {∀ y:obj {y ∈ M} ⇔ (z ∈ K ⩡ true)}")>]
    [<DataRow("exn00", "∃! z:obj {true}")>]
    [<DataRow("exn01", "∃!0 z:obj {true}")>]
    [<DataRow("exn02", "∃!1 z:obj {true}")>]
    [<DataRow("exn03", "∃!2 z:obj {true}")>]
    [<DataRow("mix00", "(A ∈ N ∧ true) ∨ ∃ x:obj {x ∈ M}")>]
    [<DataRow("mix01", "(true ∧ ¬false ∧ true ⩡ false) ∧ ∀ z:obj {z ∈ K}")>]
    [<DataRow("mix02", "((true ⇔ ∃ x:obj {x ∈ N}) ⩡ true ⩡ false) ⩡ true")>]
    [<DataRow("mix03", "((true ⇔ ∃ x:obj {x ∈ N}) ∧ (true ∧ ¬false)) ∨ ((true ⇔ ∃ x:obj {x ∈ N}) ∧ (false ⩡ true))")>]
    [<DataRow("mix04", "(true ⇔ false ∧ true ∧ false) ∨ (¬true ⇔ false ∧ ¬true ∧ false)")>]
    [<DataRow("mix05", "(true ⇔ false ∧ ¬true ⩡ false) ∨ (¬true ⇔ false ∧ true ⩡ false)")>]
    [<DataRow("mix06", "(true ⇔ false ∨ (true ∧ ¬false)) ∧ (true ⇔ false ∨ (false ⩡ true))")>]
    [<DataRow("mix07", "(∀ x:obj {x ∈ N} ∧ ∃ y:obj {y ∈ M}) ∧ true ⇔ false")>]
    [<DataRow("mix08", "(∀ x:obj {x ∈ N} ∧ ∃ y:obj {y ∈ M}) ∧ true")>]
    [<DataRow("mix09", "(∀ x:obj {x ∈ N} ∧ ∃ y:obj {y ∈ M}) ∨ (∀ x:obj {x ∈ N} ∧ true ⇒ false)")>]
    [<DataRow("mix0a", "(∀ x:obj {x ∈ N} ∧ ∃ y:obj {y ∈ M}) ∨ (¬∀ x:obj {x ∈ N} ∧ ¬∃ y:obj {y ∈ M})")>]
    [<DataRow("mix0b", "(∀ x:obj {x ∈ N} ∧ ¬∃ y:obj {y ∈ M}) ∨ (¬∀ x:obj {x ∈ N} ∧ ∃ y:obj {y ∈ M})")>]
    [<DataRow("mix0c", "(∀ x:obj {x ∈ N} ∨ ∃ y:obj {y ∈ M}) ∧ (∀ x:obj {x ∈ N} ∨ true ∨ false)")>]
    [<DataRow("mix0d", "(∃ x:obj {x ∈ N} ∨ true ⇔ false) ∨ true")>]
    [<DataRow("mix0e", "(∃ x:obj {x ∈ N} ⇔ true ⇔ false) ⇔ ∃ y:obj {y ∈ M}")>]
    [<DataRow("mix0f", "(¬(∃ x:obj {x ∈ N} ∧ true) ∨ ¬(true ⇔ false)) ∧ ((∃ x:obj {x ∈ N} ∧ true) ∨ true ⇔ false)")>]
    [<DataRow("mix10", "(¬(true ⩡ false) ∧ true ⇒ false) ∧ ∃!3 u:obj {u ∈ L}")>]
    [<DataRow("mix11", "(¬(true ⩡ false) ∧ (true ⇔ false)) ∨ (¬true ⩡ false ∧ (∃! z:obj {z ∈ N} ∧ true))")>]
    [<DataRow("mix12", "(¬(true ⩡ false) ∨ (true ⇔ true)) ∧ (¬true ⩡ false ∨ ∀ z:obj {z ∈ N})")>]
    [<DataRow("mix13", "(¬(true ∧ false) ∧ ¬(true ⇒ false)) ∨ (¬¬(true ∧ false) ∧ true ⇒ false)")>]
    [<DataRow("mix14", "(¬(true ⇒ false) ∧ (true ⩡ false)) ∨ (¬¬(true ⇒ false) ∧ ¬true ⩡ false)")>]
    [<DataRow("mix15", "(¬(true ⇔ false) ∧ (true ⩡ false)) ∨ ((true ⇔ false) ∧ ¬true ⩡ false)")>]
    [<DataRow("mix16", "(¬(true ⇔ false) ∧ ¬(true ⩡ false)) ∨ ((true ⇔ false) ∧ true ⩡ false)")>]
    [<DataRow("mix17", "(¬(true ⇔ true) ∨ ¬¬(false ⩡ true)) ∧ ((true ⇔ true) ∨ ¬(false ⩡ true))")>]
    [<DataRow("mix18", "(¬∀ x:obj {x ∈ N} ∧ ∃ y:obj {y ∈ M}) ∨ (∀ x:obj {x ∈ N} ∧ ¬∃ y:obj {y ∈ M})")>]
    [<DataRow("mix19", "(¬∀ x:obj {x ∈ N} ∧ ¬∃ y:obj {y ∈ M}) ∨ (∀ x:obj {x ∈ N} ∧ ∃ y:obj {y ∈ M})")>]
    [<DataRow("mix1a", "(¬∀ x:obj {x ∈ N} ∨ (true ⩡ false)) ∧ (∀ x:obj {x ∈ N} ∨ ¬(true ⩡ false))")>]
    [<DataRow("mix1b", "(¬∃ x:obj {x ∈ N} ∨ (true ⇔ false)) ∧ (∃ x:obj {x ∈ N} ∨ ¬true ⇔ false)")>]
    [<DataRow("mix1c", "(¬¬(true ⩡ false) ∧ ¬(true ∧ false)) ∨ (¬(true ⩡ false) ∧ true ∧ false)")>]
    [<DataRow("mix1d", "(¬¬(true ∧ false) ∨ (true ∨ false)) ∧ (¬(true ∧ false) ∨ ¬true ∨ false)")>]
    [<DataRow("mix1e", "(¬¬(true ⇔ false) ∧ (true ∧ false)) ∨ (¬(true ⇔ false) ∧ ¬true ∧ false)")>]
    [<DataRow("mix1f", "(¬¬∀ x:obj {x ∈ N} ∨ ¬(true ∨ false)) ∧ (¬∀ x:obj {x ∈ N} ∨ true ∨ false)")>]
    [<DataRow("mix20", "A() ∈ A1")>]
    [<DataRow("mix21", "true ⩡ false ⩡ true")>]
    [<DataRow("mix22", "true ⩡ false ∧ ¬false")>]
    [<DataRow("mix23", "(true ⩡ false) ∨ (∀ x:obj {x ∈ N} ⇔ false)")>]
    [<DataRow("mix24", "true ⩡ false ⇒ true ⇒ false")>]
    [<DataRow("mix25", "true ⩡ false ⇒ true ⇔ false")>]
    [<DataRow("mix26", "true ⩡ false ⇔ (true ⇔ ∃ x:obj {x ∈ N})")>]
    [<DataRow("mix27", "true ∧ false ∧ true ⇒ false")>]
    [<DataRow("mix28", "true ∧ false ∧ true ⇔ false")>]
    [<DataRow("mix29", "true ∧ false ∧ ¬¬∃ x:obj {x ∈ N}")>]
    [<DataRow("mix2a", "true ∧ false ∧ true")>]
    [<DataRow("mix2b", "(true ∧ true) ∧ false")>]
    [<DataRow("mix2c", "true ∨ false ∨ true")>]
    [<DataRow("mix2d", "true ∨ false ⇔ ¬false")>]
    [<DataRow("mix2e", "true ⇒ false ⩡ (∃ x:obj {x ∈ N} ∧ true)")>]
    [<DataRow("mix2f", "true ⇒ false ⩡ true ∧ false")>]
    [<DataRow("mix30", "true ⇒ false ∧ true ∧ false")>]
    [<DataRow("mix31", "true ⇒ false ⇔ true ∧ false")>]
    [<DataRow("mix32", "true ⇔ false ⩡ true ⩡ false")>]
    [<DataRow("mix33", "true ⇔ false ⩡ ∃ x:obj {x ∈ N ⇔ true}")>]
    [<DataRow("mix34", "(true ⇔ false) ∧ ((true ∧ ¬false) ∨ true ⇒ false)")>]
    [<DataRow("mix35", "true ⇔ false ∧ true ⩡ false")>]
    [<DataRow("mix36", "true ⇔ false ∧ ∀ x:obj {x ∈ N ⇔ true}")>]
    [<DataRow("mix37", "true ⇔ false ∧ ∃ x:obj {x ∈ N ⇔ true}")>]
    [<DataRow("mix38", "true ⇔ false ∧ ¬true ⩡ false")>]
    [<DataRow("mix39", "true ⇔ false ∨ (true ⩡ false ∧ (∃ n:obj {n ∈ N} ∧ true))")>]
    [<DataRow("mix3a", "true ⇔ false ∨ (∃ y:obj {y ∈ M} ∨ true)")>]
    [<DataRow("mix3b", "true ⇔ false ∨ ∀ x:obj {x ∈ N ⇔ true}")>]
    [<DataRow("mix3c", "true ⇔ false ∨ ∃ x:obj {x ∈ N ⇔ true}")>]
    [<DataRow("mix3d", "true ⇔ false ∨ ∃ x:obj {x ∈ N}")>]
    [<DataRow("mix3e", "true ⇔ false ⇒ (A ∈ N ∧ true)")>]
    [<DataRow("mix3f", "true ⇔ false ⇒ true ∧ false")>]
    [<DataRow("mix40", "true ⇔ false ⇒ true ⇔ false")>]
    [<DataRow("mix41", "true ⇔ false ⇒ ∀ u:obj {u ∈ K}")>]
    [<DataRow("mix42", "true ⇔ false ⇒ ∀ x:obj {x ∈ N ⇔ true}")>]
    [<DataRow("mix43", "true ⇔ false ⇒ ∃ x:obj {x ∈ N ⇔ true}")>]
    [<DataRow("mix44", "(true ⇔ false) ⇔ true ⩡ false")>]
    [<DataRow("mix45", "true ⇔ false ⇔ ∀ x:obj {x ∈ N ⇔ true}")>]
    [<DataRow("mix46", "true ⇔ false ⇔ ∃ x:obj {x ∈ N ⇔ true}")>]
    [<DataRow("mix47", "true ⇔ false ⇔ true")>]
    [<DataRow("mix48", "¬(A ∈ N ⇔ true) ⇒ ∃ x:obj {x ∈ M}")>]
    [<DataRow("mix49", "¬((true ⩡ false) ∧ true ⇒ false)")>]
    [<DataRow("mix4a", "¬(true ∧ false ∧ ∃ x:obj {x ∈ N})")>]
    [<DataRow("mix4b", "¬((true ⇒ false) ⩡ true ∧ false)")>]
    [<DataRow("mix4c", "¬((true ⇒ false) ∨ true ∧ false)")>]
    [<DataRow("mix4d", "¬(true ⇒ false ⇔ ∀ z:obj {z ∈ K})")>]
    [<DataRow("mix4e", "¬((true ⇔ false) ⩡ true ⩡ false)")>]
    [<DataRow("mix4f", "¬(true ⇔ false ∧ ∀ x:obj {x ∈ N})")>]
    [<DataRow("mix50", "¬(true ⇔ false ∨ ∃ x:obj {x ∈ N})")>]
    [<DataRow("mix51", "¬((true ⇔ false) ⇒ true ⩡ false)")>]
    [<DataRow("mix52", "¬((true ⇔ false) ⇔ true ⩡ false)")>]
    [<DataRow("mix53", "¬(∀ x:obj {x ∈ N} ⩡ ∃ y:obj {y ∈ M})")>]
    [<DataRow("mix54", "¬(∀ x:obj {x ∈ N} ∨ true ⩡ false)")>]
    [<DataRow("mix54", "¬(∀ x:obj {x ∈ N} ⇒ ∃ y:obj {y ∈ M})")>]
    [<DataRow("mix56", "¬(∀ x:obj {x ∈ N} ⇒ ¬true ⇔ false)")>]
    [<DataRow("mix57", "¬(∀ x:obj {x ∈ N} ⇔ ∃ y:obj {y ∈ M})")>]
    [<DataRow("mix58", "¬(∃ x:obj {x ∈ M} ⇒ ¬¬true ⩡ false)")>]
    [<DataRow("mix59", "¬(¬true ⇒ false ⇒ ∀ z:obj {z ∈ K})")>]
    [<DataRow("mix5a", "¬(¬true ⇒ false ⇒ ¬∀ z:obj {z ∈ K})")>]
    [<DataRow("mix5b", "¬(¬(true ⇔ false) ∨ ¬true ⩡ false)")>]
    [<DataRow("mix5c", "¬(¬∀ x:obj {x ∈ N} ∨ ¬∃ y:obj {y ∈ M})")>]
    [<DataRow("mix5d", "¬(¬¬∃ x:obj {x ∈ N} ∨ ¬true ⇒ false)")>]
    [<DataRow("mix5e", "¬true ⩡ false ⩡ ∃ z:obj {z ∈ N ⇒ false}")>]
    [<DataRow("mix5f", "¬true ⩡ false ∧ ∀ z:obj {z ∈ N ⇒ false}")>]
    [<DataRow("mix60", "¬true ⩡ false ∧ ∃ z:obj {z ∈ N ⇒ false}")>]
    [<DataRow("mix61", "¬true ⩡ false ∨ ∀ z:obj {z ∈ N ⇒ false}")>]
    [<DataRow("mix62", "¬true ⩡ false ∨ ∃ z:obj {z ∈ N ⇒ false}")>]
    [<DataRow("mix63", "¬(true ⩡ false) ⇒ (∀ z:obj {z ∈ N} ⇒ false)")>]
    [<DataRow("mix64", "¬true ⩡ false ⇒ ∀ z:obj {z ∈ N ⇒ false}")>]
    [<DataRow("mix65", "¬true ⩡ false ⇒ ∃ z:obj {z ∈ N ⇒ false}")>]
    [<DataRow("mix66", "¬true ⩡ false ⇔ ∀ z:obj {z ∈ N ⇒ false}")>]
    [<DataRow("mix67", "¬true ⩡ false ⇔ ∃ z:obj {z ∈ N ⇒ false}")>]
    [<DataRow("mix68", "¬true ⩡ false")>]
    [<DataRow("mix69", "¬(true ∧ ¬false) ∨ (∃ x:obj {x ∈ N} ∨ true)")>]
    [<DataRow("mix6a", "¬true ∧ false")>]
    [<DataRow("mix6b", "¬(true ⇒ false) ∧ ¬true ∧ false")>]
    [<DataRow("mix6c", "¬true ⇔ false ∧ ¬∃ x:obj {x ∈ N}")>]
    [<DataRow("mix6d", "¬(true ⇔ false) ∨ ¬true ⇒ false")>]
    [<DataRow("mix6e", "¬true ⇔ false")>]
    [<DataRow("mix6f", "¬∀ n:Nat {n ∈ N ∧ true ⩡ false}")>]
    [<DataRow("mix70", "¬∀ x:obj {x ∈ N ⇔ true}")>]
    [<DataRow("mix71", "¬∀ x:obj {x ∈ N} ∧ ∀ x:obj {x ∈ N}")>]
    [<DataRow("mix72", "¬∀ x:obj {x ∈ N} ∧ ¬true ⩡ false")>]
    [<DataRow("mix73", "¬∀ x:obj {x ∈ N} ∨ ∃ y:obj {y ∈ M}")>]
    [<DataRow("mix74", "¬∀ x:obj {x ∈ N} ∨ ¬∃ y:obj {¬y ∈ M}")>]
    [<DataRow("mix75", "¬∀ x:obj {x ∈ N} ⇒ (true ∧ ¬false)")>]
    [<DataRow("mix76", "¬∀ x:obj {x ∈ N}")>]
    [<DataRow("mix77", "¬∃ n:Nat {n ∈ N ∧ true ⩡ false}")>]
    [<DataRow("mix78", "¬∃ x:obj {x ∈ N ⇔ true}")>]
    [<DataRow("mix79", "¬¬(true ⩡ false) ∨ true ⇔ false")>]
    [<DataRow("mix7a", "¬¬true ∨ ¬true ⩡ false")>]
    [<DataRow("mix7b", "¬true ∨ (true ⇒ false ∧ ∃ y:obj {y ∈ N})")>]
    [<DataRow("mix7c", "A ∈ A1")>]
    [<DataRow("mix7d", "A() ∈ A1")>]
    [<DataRow("mix7e", "false ⩡ true")>]
    [<DataRow("mix7f", "false ∧ true")>]
    [<DataRow("mix80", "false ∨ true")>]
    [<DataRow("mix81", "false ⇔ true")>]
    [<DataRow("mix82", "false")>]
    [<DataRow("mix83", "q ⇒ (¬(true ⩡ false) ∧ true ⇔ false)")>]
    [<DataRow("mix84", "q ⇒ ∀ x:obj {x ∈ N}")>]
    [<DataRow("mix85", "true ⩡ false")>]
    [<DataRow("mix86", "true ∧ false ⩡ true")>]
    [<DataRow("mix86_", "true ∧ (false ⩡ true)")>]
    [<DataRow("mix87", "true ∧ ¬false")>]
    [<DataRow("mix88", "true ∧ false")>]
    [<DataRow("mix89", "true ∨ false")>]
    [<DataRow("mix8a", "true ⇒ false")>]
    [<DataRow("mix8b", "true ⇔ false ⩡ true")>]
    [<DataRow("mix8b_", "true ⇔ false ⩡ true")>]
    [<DataRow("mix8c", "true ⇔ ∃ y:obj {y ∈ M}")>]
    [<DataRow("mix8d", "true ⇔ ¬false")>]
    [<DataRow("mix8e", "true ⇔ false")>]
    [<DataRow("mix8f", "true")>]
    [<DataRow("subscr00", """x( y )""")>]
    [<DataRow("subscr01", """x(y)""")>]
    [<DataRow("subscr02", """x[y]""")>]
    [<DataRow("subscr03", """x[y]'""")>]
    [<DataRow("subscr04", """x.y'""")>]
    [<DataRow("subscr05", """x.y""")>]
    [<DataRow("subscr06", """x[ y ]""")>]
    [<DataRow("subscr07", """z[x[y]]""")>]
    [<DataRow("subscr08", """z[x, y[i]]""")>]
    [<DataRow("subscr09", """x[y]""")>]
    [<DataRow("subscr10", """x[@1,@3]""")>]
    [<DataRow("subscr11", """x[$1]""")>]
    [<DataRow("subscr12", """x[y]""")>]
    [<DataRow("subscr13", """x[@1]""")>]
    [<DataRow("subscr14", """x[$1,@1]""")>]
    [<DataRow("subscr15", """x[y,@2]""")>]
    [<DataRow("subscr16", """x[ $1]""")>]
    [<DataRow("subscr17", """$1!""")>]
    [<DataRow("subscr18", """$1""")>]
    [<DataRow("subscr19", """$1'""")>]
    [<DataRow("subscr20", """-$1""")>]
    [<DataRow("subscr21", """x($1)""")>]
    [<DataRow("subscr22", """x($1)""")>]
    [<DataRow("subscr23", """x( $1 )""")>]
    [<DataRow("subscr24", """x[$1]""")>]
    [<DataRow("subscr25", """x[ $1 ]""")>]
    [<DataRow("subscr26", """x[ $1 ]""")>]
    [<DataRow("subscr27", """ClosedOpenRange($1)""")>]
    [<DataRow("subscr28", """x[$1,$1]""")>]
    [<DataRow("subscr29", """x[ $1 ]""")>]
    [<DataRow("subscr20", """x[$1]""")>]
    [<DataRow("subscr21", """x[ $1]""")>]
    [<DataRow("self01", """self.parent""")>]
    [<DataRow("self02", """parent.self""")>]
    [<DataRow("self03", LiteralSelf)>]
    [<DataRow("self04", """parent(self)""")>]
    [<DataRow("self05", """self (self)""")>]
    [<DataRow("self06", """self( parent)""")>]
    [<DataRow("self07", """parent ( self )""")>]
    [<DataRow("self08", """self[parent]""")>]
    [<DataRow("self09", """parent[self]""")>]
    [<DataRow("self10", """self [ self ]""")>]
    [<DataRow("self11", LiteralSelf)>]
    [<DataRow("self12", LiteralParent)>]
    [<DataRow("qual01", """PascalId.PascalId""")>]
    [<DataRow("qual02", """PascalId().PascalId()""")>]
    [<DataRow("qual03", """PascalId(PascalId)""")>]
    [<DataRow("qual04", """PascalId(PascalId)'""")>]
    [<DataRow("qual05", """PascalId( PascalId )'""")>]
    [<DataRow("qual06", """PascalId[PascalId]'""")>]
    [<DataRow("qual07", """PascalId[ PascalId ]'""")>]
    [<DataRow("qual08", """Xx'""")>]
    [<DataRow("qual08a", """Xx.Yy().Zz'""")>]
    [<DataRow("qual08b", """(Xx.Yy().Zz)'""")>]
    [<DataRow("qual09", """PascalId[PascalId,Nat]'""")>]
    [<DataRow("qual10", """(PascalId[PascalId,Nat])'""")>]
    [<DataRow("qual11", """PascalId.PascalId'""")>]
    [<DataRow("qual11a", """(PascalId.PascalId)'""")>]
    [<DataRow("qual12", """PascalId( PascalId )""")>]
    [<DataRow("qual13", """PascalId[PascalId]""")>]
    [<DataRow("qual14", """PascalId[ PascalId ]""")>]
    [<DataRow("qual15", """PascalId[PascalId,Nat]""")>]
    [<DataRow("qual16", """PascalId[PascalId,Nat]""")>]
    [<DataRow("qual17", """x(@1)""")>]
    [<DataRow("qual18", """x( @1 )""")>]
    [<DataRow("qual19", """x[@1]""")>]
    [<DataRow("qual20", """x[ @1 ]""")>]
    [<DataRow("qual21", """1.1""")>]
    [<DataRow("qual22", """@4(@2)""")>]
    [<DataRow("qual23", """1( 1 )""")>]
    [<DataRow("qual24", """@1[@1]""")>]
    [<DataRow("qual25", """@1[ @1 ]""")>]
    [<DataRow("qual26", """x.@1""")>]
    [<TestMethod>]
    member this.TestExpressionSuccess (no:string, expr:string) =
        let result = run (expression .>> eof) expr
        let actual = sprintf "%O" result
        printf "%O" actual
        Assert.IsTrue(actual.StartsWith("Success:"))

    [<DataRow("00a", "(1 + x)")>]
    [<DataRow("00b", "(1)")>]
    [<DataRow("00d", "(1+ )")>]
    [<DataRow("00f", "(1+)")>]
    [<DataRow("01a", "(@1 + x)")>]
    [<DataRow("01b", "(@1)")>]
    [<DataRow("01d", "(@1+ )")>]
    [<DataRow("01f", "(@1+)")>]
    [<DataRow("02a", "(x + 1)")>]
    [<DataRow("02a", "(x + @1)")>]
    [<DataRow("02b", "(x)")>]
    [<DataRow("02d", "(x+ )")>]
    [<DataRow("02f", "(x+)")>]
    [<DataRow("03a", "(1 = x)")>]
    [<DataRow("03b", "(1)")>]
    [<DataRow("04a", "(@1 = x)")>]
    [<DataRow("04b", "(@1)")>]
    [<DataRow("04d", "(@1= )")>]
    [<DataRow("04f", "(@1=)")>]
    [<DataRow("05a", "(x = 1)")>]
    [<DataRow("05a", "(x = @1)")>]
    [<DataRow("05b", "(x)")>]
    [<TestMethod>]
    member this.TestInfixOperationSuccess (no:string, expr:string) =
        let result = run (pInfixExpr .>> eof) expr
        let actual = sprintf "%O" result
        printf "%O" actual
        Assert.IsTrue(actual.StartsWith("Success:"))

    [<DataRow("00c", "(1 + )")>]
    [<DataRow("00e", "(1 +)")>]
    [<DataRow("01", "false()")>]
    [<DataRow("01_", "false ()")>]
    [<DataRow("01a", "false().x[2]")>]
    [<DataRow("01b", "false[2]")>]
    [<DataRow("01c", "false.F().x[2]")>]
    [<DataRow("01c_", "(@1 + )")>]
    [<DataRow("01e", "(@1 +)")>]
    [<DataRow("02", "and(a,b)()")>]
    [<DataRow("02a", "and(a,b)().x[2]")>]
    [<DataRow("02b", "and(a,b).x[2]")>]
    [<DataRow("02c", "and(a,b).F().x[2]")>]
    [<DataRow("02c_", "(x + )")>]
    [<DataRow("02e", "(x +)")>]
    [<DataRow("03", "mcases ( | true: true ? false )()")>]
    [<DataRow("03a", "mcases ( | true: true ? false )().x[2]")>]
    [<DataRow("03b", "mcases ( | true: true ? false )[2]")>]
    [<DataRow("03c", "mcases ( | true: true ? false ).F().x[2]")>]
    [<DataRow("03c_", "(1 = )")>]
    [<DataRow("03d", "(1= )")>]
    [<DataRow("03e", "(1 =)")>]
    [<DataRow("03f", "(1=)")>]
    [<DataRow("04c", "(@1 = )")>]
    [<DataRow("04e", "(@1 =)")>]
    [<DataRow("05c", "(x = )")>]
    [<DataRow("05e", "(x =)")>]
    [<DataRow("05d", "(x= )")>]
    [<DataRow("05f", "(x=)")>]
    [<DataRow("06", "a * b + (c d)")>]
    [<DataRow("07", LiteralPre)>]
    [<DataRow("08", """premise """)>]
    [<DataRow("09", """parent. self""")>]
    [<DataRow("subscr00", """x'(y)""")>]
    [<DataRow("subscr01", """x'( y )""")>]
    [<DataRow("subscr02", """x'[y]""")>]
    [<DataRow("subscr03", """x'[ y ]""")>]
    [<DataRow("subscr04", """x'.y""")>]
    [<DataRow("subscr04a", """x. y""")>]
    [<DataRow("subscr05", """x [y]""")>]
    [<DataRow("subscr06", """x!$1""")>]
    [<DataRow("subscr07", """x!y""")>]
    [<DataRow("subscr08", """x!1""")>]
    [<DataRow("subscr09", """$1.$1""")>]
    [<DataRow("subscr10", """x . $1""")>]
    [<DataRow("subscr11", """s ( $1 )""")>]
    [<DataRow("subscr12", """x [$1]""")>]
    [<DataRow("subscr13", """x [ $1 ]""")>]
    [<DataRow("subscr14", """x [ $1]""")>]
    [<DataRow("subscr15", """$1!.Test(1)""")>]
    [<DataRow("subscr16", """$1($1)""")>]
    [<DataRow("subscr16a", """$1( $1 )""")>]
    [<DataRow("subscr17", """$1'($1)""")>]
    [<DataRow("subscr18", """$1'( $1 )""")>]
    [<DataRow("subscr19", """$1[$1]""")>]
    [<DataRow("subscr20", """$1'[$1]""")>]
    [<DataRow("subscr21", """$1[ $1 ]""")>]
    [<DataRow("subscr22", """$1'[ $1 ]""")>]
    [<DataRow("subscr23", """$1[$1]""")>]
    [<DataRow("subscr24", """$1'[$1]""")>]
    [<DataRow("subscr25", """$1[$1 ]""")>]
    [<DataRow("subscr26", """$1'[ $1 ]""")>]
    [<DataRow("subscr27", """x'[$1]""")>]
    [<DataRow("subscr28", """$1'!.Test(1)""")>]
    [<DataRow("subscr29", """$1!'.Test(1)""")>]
    [<DataRow("subscr30", """x.-$1""")>]
    [<DataRow("subscr31", """x'.$1""")>]
    [<DataRow("subscr32", """$1 .$1""")>]
    [<DataRow("subscr33", """$1. $1""")>]
    [<DataRow("subscr34", """$1 . $1""")>]
    [<DataRow("subscr35", """$1!.$1""")>]
    [<DataRow("subscr36", """$1'! $1""")>]
    [<DataRow("subscr37", """x.$1""")>]
    [<DataRow("qual01", """Xx'.Yy'.Zz""")>]
    [<DataRow("qual02", """PascalId. PascalId""")>]
    [<DataRow("qual03", """PascalId . PascalId""")>]
    [<DataRow("qual04", """PascalId'(PascalId)""")>]
    [<DataRow("qual05", """PascalId'( PascalId )""")>]
    [<DataRow("qual06", """PascalId'[PascalId]""")>]
    [<DataRow("qual07", """PascalId'[ PascalId ]""")>]
    [<DataRow("qual08", """Xx'.Yy().Zz""")>]
    [<DataRow("qual09", """PascalId'[PascalId,Nat]""")>]
    [<DataRow("qual10", """PascalId'[PascalId,Nat]""")>]
    [<DataRow("qual11", """PascalId'.PascalId""")>]
    [<DataRow("qual12", """1. 1""")>]
    [<DataRow("qual13", """1 . 1""")>]
    [<DataRow("qual14", """@1 (@1)""")>]
    [<DataRow("qual15", """@1 ( @1 )""")>]
    [<DataRow("qual16", """@1 [@1]""")>]
    [<DataRow("qual17", """@1 [ @1 ]""")>]
    [<DataRow("qual18", """@1[@1,]>""")>]
    [<DataRow("qual19", """@1 [@1,]""")>]
    [<DataRow("qual20", """@1[ @1 ,]""")>]
    [<DataRow("qual21", """@1 [ @1 ,]""")>]
    [<DataRow("qual22", """x. @1""")>]
    [<DataRow("qual23", """x . @1""")>]
    [<DataRow("qual24", """x'(@1)""")>]
    [<DataRow("qual25", """s'( @1 )""")>]
    [<DataRow("qual26", """x'[@1]""")>]
    [<DataRow("qual27", """x'[ @1 ]""")>]
    [<DataRow("qual28", """x'.@1""")>]
    [<DataRow("qual29", """1 .1""")>]
    [<TestMethod>]
    member this.TestExpressionFailure (no:string, expr:string) =
        let result = run (expression .>> eof) expr
        let actual = sprintf "%O" result
        printf "%O" actual
        Assert.IsTrue(actual.StartsWith("Failure:"))

    [<DataRow("01", "false()")>]
    [<DataRow("01a", "false().x[2]")>]
    [<DataRow("01b", "false.x[2]")>]
    [<DataRow("01c", "false.F().x[2]")>]
    [<TestMethod>]
    member this.TestPredicateWithQualificationFailure (no:string, expr:string) =
        let result = run (predicateWithQualification .>> eof) expr
        let actual = sprintf "%O" result
        printf "%O" actual
        Assert.IsTrue(actual.StartsWith("Failure:"))

    [<DataRow("01", "a * b + (c d)")>]
    [<DataRow("02", "a ∧ ∀ x:obj {x  N}")>]
    [<TestMethod>]
    member this.TestPredicateContentFailure (no:string, expr:string) =
        let result = run (predContent .>> eof) expr
        let actual = sprintf "%O" result
        printf "%O" actual
        Assert.IsTrue(actual.StartsWith("Failure:"))

    [<DataRow("01", "{a * b + (c d)}")>]
    [<DataRow("02", "{a ∧ ∀ x:obj {x  N}}")>]
    [<DataRow("03", """PrecedingResults$1(x,y)""")>]
    [<DataRow("04", "undet")>]
    [<DataRow("05", """x! !""")>]
    [<DataRow("06", """~ ~x""")>]
    [<DataRow("07", """exn$0 x,y,z:obj(true)""")>]
    [<TestMethod>]
    member this.TestPredicateInstanceBlocktFailure (no:string, expr:string) =
        let result = run (predicateInstanceBlock .>> eof) expr
        let actual = sprintf "%O" result
        printf "%O" actual
        Assert.IsTrue(actual.StartsWith("Failure:"))

    [<DataRow("01", "{a * b + (c d)}")>]
    [<DataRow("02", "{a ∧ ∀ x:obj {x  N}}")>]
    [<TestMethod>]
    member this.TestPredicateDefinitionBlocktFailure (no:string, expr:string) =
        let result = run (predicateDefinitionBlock .>> eof) expr
        let actual = sprintf "%O" result
        printf "%O" actual
        Assert.IsTrue(actual.StartsWith("Failure:"))


