namespace TestFpl1Parser.LowLevel

open FParsec
open Fpl1Parser.Grammar
open Fpl0Base.Primitives
open Microsoft.VisualStudio.TestTools.UnitTesting

[<TestClass>]
type TestVariableTypes () =
    [<DataRow("01", LiteralObjL)>]
    [<DataRow("02", LiteralObj)>]
    [<DataRow("03", LiteralFuncL)>]
    [<DataRow("04", LiteralFunc)>]
    [<DataRow("05", LiteralPredL)>]
    [<DataRow("06", LiteralPred)>]
    [<DataRow("07", LiteralIndL)>]
    [<DataRow("08", LiteralInd)>]
    [<DataRow("09", "SomeClass")>]
    [<DataRow("10", "Nat")>]
    [<DataRow("11", "template")>]
    [<DataRow("12", LiteralTpl)>]
    [<DataRow("13", "templateTest")>]
    [<DataRow("14", "tplTest")>]
    [<DataRow("15", "function(a,b:obj)->obj")>]
    [<DataRow("16", "function(a,b:obj)->pred")>]
    [<DataRow("17", "*function(a,b:obj)->* pred [ind] [obj]")>]
    [<DataRow("18", "*function(a,b:obj)->pred[tpl]")>]
    [<DataRow("19", "func(a:ind,b:pred)->func")>]
    [<DataRow("20", "func(a:ind,b:pred)->func(x,y:obj)->obj")>]
    [<DataRow("21", "predicate()")>]
    [<DataRow("22", "function()->obj")>]
    [<DataRow("23", "*predicate()[Nat]")>]
    [<DataRow("24", "pred(x:ind)")>]
    [<DataRow("25", "*pred(x:ind)[ ind ,ind]")>]
    [<DataRow("26", "pred(x , y, z:obj)")>]
    [<DataRow("27", "*pred(x , y, z:obj) [ obj]")>]
    [<DataRow("28", "index")>]
    [<DataRow("29", "ind")>]
    [<DataRow("30", "*ind[ind]")>]
    [<DataRow("31", "template")>]
    [<DataRow("32", "tpl")>]
    [<DataRow("33", "*tpl[Nat]")>]
    [<DataRow("34", "SomeClass")>]
    [<DataRow("35", "*SomeClass[obj]")>]
    [<DataRow("36", "templateTest")>]
    [<DataRow("37", "tplTest")>]
    [<DataRow("38", "*tplTest[ind,ind,ind]")>]
    [<TestMethod>]
    member this.TestVariableTypeSuccess (no:string, input:string) =
        let result = run (variableType .>> eof) input
        let actual = sprintf "%O" result
        printf "%O" actual
        Assert.IsTrue(actual.StartsWith("Success:"))

    [<DataRow("01", "template(x:ind,y:ind)")>]
    [<DataRow("02", "template(x:ind,y:T)->obj")>]
    [<DataRow("03", "tpl()")>]
    [<DataRow("04", "template(x:func()->func()->func()->func()->ind)")>]
    [<DataRow("05", "tpl(x,y,z:pred())")>]
    [<DataRow("06", "templateTest(x,y,z:pred())")>]
    [<DataRow("07", "tplTest(x:ind)")>]
    [<DataRow("08", "tplTest(x:ind)")>]
    [<DataRow("09", "templateTest()")>]
    [<DataRow("10", "tplTest(x:obj)")>]
    [<DataRow("11", "tpl(a:ind,b:pred,c:obj,d:@T,e:T,f:tpl)")>]
    [<DataRow("12", "tplTest  (x:ind)")>]
    [<DataRow("13", "tplTest(x:obj())")>]
    [<DataRow("14", "Set(y:Nat)")>]
    [<DataRow("15", "SomeClass[x:ind]")>]
    [<DataRow("16", "object[]")>]
    [<DataRow("17", "object[x:ind]")>]
    [<DataRow("18", "obj[x,y:pred]")>]
    [<DataRow("19", "object()")>]
    [<DataRow("20", "obj()")>]
    [<DataRow("21", "function ")>]
    [<DataRow("22", "func ")>]
    [<DataRow("23", "predicate ")>]
    [<DataRow("24", "pred ")>]
    [<DataRow("25", "func[]")>]
    [<DataRow("26", "pred[]")>]
    [<DataRow("27", "index[obj]")>]
    [<DataRow("28", "index(x:obj)")>]
    [<DataRow("29", "SomeClass[1]")>]
    [<DataRow("30", "+Nat()")>]
    [<DataRow("31", "predicate ()")>]
    [<DataRow("32", "+Nat[y:ind]")>]
    [<DataRow("33", "index[x:ind,y:ind]")>]
    [<DataRow("34", "SomeClass[y:ind,z:ind]")>]
    [<DataRow("35", "object [x,y,z]")>]
    [<DataRow("36", "obj[x,y:obj]")>]
    [<DataRow("37", "function[x:obj]")>]
    [<DataRow("38", "SomeClass[y:ind,z:ind]")>]
    [<DataRow("39", "index()")>]
    [<DataRow("40", "ind[SomeClass]")>]
    [<DataRow("41", "index()")>]
    [<DataRow("42", "SomeClass[x:SomeOtherClass]")>]
    [<DataRow("43", "@Nat[]")>]
    [<DataRow("44", "Nat()()")>]
    [<DataRow("45", "index()")>]
    [<DataRow("46", "pred()()")>]
    [<DataRow("47", "tpl[x:index   ]")>]
    [<DataRow("48", "templateTest[x:ind ,y:pred]")>]
    [<DataRow("49", "tplTest[]")>]
    [<DataRow("50", "func()->obj()")>]
    [<DataRow("51", "func()->tpl()")>]
    [<DataRow("52", "val()")>]
    [<DataRow("53", "validity()")>]
    [<TestMethod>]
    member this.TestVariableTypeFailure (no:string, input:string) =
        let result = run (variableType .>> eof) input
        let actual = sprintf "%O" result
        printf "%O" actual
        Assert.IsTrue(actual.StartsWith("Failure:"))
