<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.2" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
        <PackageReference Include="MSTest" Version="4.3.3" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="MSTestSettings.fs" />
        <Compile Include="FileMgmt\TestPathEquivalentUri.fs" />
        <Compile Include="FileMgmt\TestDotNetDownload.fs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Fpl2Interpreter\Fpl2Interpreter.fsproj" />
        <ProjectReference Include="..\Fpl3LanguageServer\Fpl3LanguageServer.fsproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Update="FSharp.Core" Version="10.1.301" />
    </ItemGroup>

</Project>